
-- 1INF33_2025-1_Lab1_Calificada_DDL
-- Por: LOW y ACB

CREATE TABLE AP_AEROPUERTOS (
    AEROPUERTO_ID NUMBER NOT NULL,
    NOMBRE        VARCHAR2(50 BYTE) NOT NULL,
    HORA_APERTURA DATE NOT NULL,
    HORA_CIERRE   DATE NOT NULL,
    CIUDAD_ID     NUMBER NOT NULL,
    PAIS_ID       NUMBER NOT NULL
);

COMMENT ON COLUMN AP_AEROPUERTOS.AEROPUERTO_ID IS
    'Numero identificador del aeropuerto';

COMMENT ON COLUMN AP_AEROPUERTOS.NOMBRE IS
    'NOMBRE del aeropuerto';

COMMENT ON COLUMN AP_AEROPUERTOS.HORA_APERTURA IS
    'Hora de apertura del aeropuerto';

COMMENT ON COLUMN AP_AEROPUERTOS.HORA_CIERRE IS
    'Hora de cierre del aeropuerto';

ALTER TABLE AP_AEROPUERTOS ADD CONSTRAINT PK_AEROPUERTOS PRIMARY KEY ( AEROPUERTO_ID );

CREATE TABLE AP_AVIONES (
    AVION_ID      NUMBER NOT NULL,
    NRO_PLACA     NUMBER NOT NULL,
    MODELO        VARCHAR2(30 BYTE) NOT NULL,
    CAP_PASAJEROS NUMBER NOT NULL,
    CAP_BODEGA    NUMBER NOT NULL,
    KM_MAX_VUELO  NUMBER NOT NULL,
    ESTADO        CHAR(1 BYTE) NOT NULL,
    MARCA_ID      NUMBER NOT NULL
);

COMMENT ON COLUMN AP_AVIONES.AVION_ID IS
    'Numero identificador del avion (diferente a su placa)';

COMMENT ON COLUMN AP_AVIONES.NRO_PLACA IS
    'Numero de placa o matricula';

COMMENT ON COLUMN AP_AVIONES.MODELO IS
    'MODELO del avion';

COMMENT ON COLUMN AP_AVIONES.CAP_PASAJEROS IS
    'Capacidad maxima de pasajeros del avion';

COMMENT ON COLUMN AP_AVIONES.CAP_BODEGA IS
    'Capacidad maxima de bodega';

COMMENT ON COLUMN AP_AVIONES.KM_MAX_VUELO IS
    'Distancia maxima en kilometros de vuelo continuo que puede tener el avion';

COMMENT ON COLUMN AP_AVIONES.ESTADO IS
    'ESTADO del avion:
A: ACTIVO
I: InACTIVO';

ALTER TABLE AP_AVIONES ADD CONSTRAINT PK_AVIONES PRIMARY KEY ( AVION_ID );

CREATE TABLE AP_BOLETOS (
    BOLETO_ID         NUMBER NOT NULL,
    NRO_SERIE         VARCHAR2(10 BYTE) NOT NULL,
    CORRELATIVO       NUMBER NOT NULL,
    FECHA_EMISION     DATE NOT NULL,
    CATEGORIA         CHAR(1 BYTE) NOT NULL,
    PRECIO_BOLETO_USD NUMBER(6, 2) NOT NULL,
    PASAJERO_ID       NUMBER NOT NULL,
    VUELO_ID          CHAR(6 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_BOLETOS.BOLETO_ID IS
    'Numero identificador del boleto (podria ser el CORRELATIVO)';

COMMENT ON COLUMN AP_BOLETOS.NRO_SERIE IS
    'Numero de serie del boleto que no siempre sera numerico.';

COMMENT ON COLUMN AP_BOLETOS.CORRELATIVO IS
    'Numero CORRELATIVO del boleto';

COMMENT ON COLUMN AP_BOLETOS.FECHA_EMISION IS
    'Fecha de emision del boleto';

COMMENT ON COLUMN AP_BOLETOS.CATEGORIA IS
    'Categoria del boleto:
- P: Primera clase
- E: Ejecutiva';

COMMENT ON COLUMN AP_BOLETOS.PRECIO_BOLETO_USD IS
    'Precio en dolares ESTADOunidenses del boleto';

ALTER TABLE AP_BOLETOS ADD CONSTRAINT PK_BOLETOS PRIMARY KEY ( BOLETO_ID );

CREATE TABLE AP_CARGOS (
    CARGO_ID    NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(20 BYTE) NOT NULL,
    ACTIVO      NUMBER NOT NULL
);

COMMENT ON COLUMN AP_CARGOS.CARGO_ID IS
    'Numero identificador del cargo';

COMMENT ON COLUMN AP_CARGOS.DESCRIPCION IS
    'Puede ser:
- Piloto (a)
- Copiloto (a)
- Jefe (a) de cabina
- Aeromozo (a)';

COMMENT ON COLUMN AP_CARGOS.ACTIVO IS
    '0: inACTIVO
1: ACTIVO';

ALTER TABLE AP_CARGOS ADD CONSTRAINT PK_CARGOS PRIMARY KEY ( CARGO_ID );

CREATE TABLE AP_CIUDADES (
    CIUDAD_ID NUMBER NOT NULL,
    NOMBRE    VARCHAR2(30 BYTE) NOT NULL,
    PAIS_ID   NUMBER NOT NULL
);

COMMENT ON COLUMN AP_CIUDADES.CIUDAD_ID IS
    'Numero identificador de la ciudad';

COMMENT ON COLUMN AP_CIUDADES.NOMBRE IS
    'NOMBRE de la ciudad';

COMMENT ON COLUMN AP_CIUDADES.PAIS_ID IS
    'Pais al que pertenece la ciudad';

ALTER TABLE AP_CIUDADES ADD CONSTRAINT PK_CIUDADES PRIMARY KEY ( CIUDAD_ID,
                                                                 PAIS_ID );

CREATE TABLE AP_EMPLEADOS_VUELOS (
    VUELO_ID    CHAR(6 BYTE) NOT NULL,
    EMPLEADO_ID CHAR(6 BYTE) NOT NULL
);

ALTER TABLE AP_EMPLEADOS_VUELOS ADD CONSTRAINT PK_EMPLEADOS_VUELOS PRIMARY KEY ( VUELO_ID,
                                                                                 EMPLEADO_ID );

CREATE TABLE AP_EQUIPAJES (
    TIPO_EQUIPAJE_ID NUMBER NOT NULL,
    DESCRIPCION      VARCHAR2(20 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_EQUIPAJES.TIPO_EQUIPAJE_ID IS
    'Numero identificador del tipo de equipaje';

COMMENT ON COLUMN AP_EQUIPAJES.DESCRIPCION IS
    'Los tipos de equipaje pueden ser:
- "De Cabina"
- "De Bodega"
- "Carga Especial"';

ALTER TABLE AP_EQUIPAJES ADD CONSTRAINT PK_EQUIPAJES PRIMARY KEY ( TIPO_EQUIPAJE_ID );

CREATE TABLE AP_EQUIPAJES_BOLETOS (
    BOLETO_ID           NUMBER NOT NULL,
    TIPO_EQUIPAJE_ID    NUMBER NOT NULL,
    DESCRIPCION         VARCHAR2(30 BYTE) NOT NULL,
    PRECIO_EQUIPAJE_USD NUMBER(6, 2) NOT NULL,
    PESO                NUMBER(6, 2) NOT NULL
);

ALTER TABLE AP_EQUIPAJES_BOLETOS ADD CONSTRAINT PK_EQUIPAJES_BOLETOS PRIMARY KEY ( BOLETO_ID,
                                                                                  TIPO_EQUIPAJE_ID );

CREATE TABLE AP_MANT_AVIONES (
    AVION_ID              NUMBER NOT NULL,
    TIPO_MANTENIMIENTO_ID NUMBER NOT NULL,
    FECHA_INICIO_EST      DATE NOT NULL,
    FECHA_FIN_EST         DATE NOT NULL
);

COMMENT ON COLUMN AP_MANT_AVIONES.FECHA_INICIO_EST IS
    'Fecha de inicio estimada del mantenimiento';

COMMENT ON COLUMN AP_MANT_AVIONES.FECHA_FIN_EST IS
    'Fecha de fin estimada del mantenimiento';

ALTER TABLE AP_MANT_AVIONES ADD CONSTRAINT PK_MANT_AVIONES PRIMARY KEY ( AVION_ID,
                                                                         TIPO_MANTENIMIENTO_ID );

CREATE TABLE AP_MARCAS (
    MARCA_ID    NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(20 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_MARCAS.MARCA_ID IS
    'Numero identificador de la marca';

COMMENT ON COLUMN AP_MARCAS.DESCRIPCION IS
    'Descripcion o NOMBRE de la marca';

ALTER TABLE AP_MARCAS ADD CONSTRAINT PK_MARCAS PRIMARY KEY ( MARCA_ID );

CREATE TABLE AP_PAISES (
    PAIS_ID NUMBER NOT NULL,
    NOMBRE  VARCHAR2(30 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_PAISES.PAIS_ID IS
    'Numero identificador del pais';

COMMENT ON COLUMN AP_PAISES.NOMBRE IS
    'NOMBRE del pais';

ALTER TABLE AP_PAISES ADD CONSTRAINT PK_PAISES PRIMARY KEY ( PAIS_ID );

CREATE TABLE AP_PARENTESCOS (
    PASAJERO_ID NUMBER NOT NULL,
    PARIENTE_ID NUMBER NOT NULL,
    VINCULO     VARCHAR2(20 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_PARENTESCOS.PASAJERO_ID IS
    'Pasajero asociado';

COMMENT ON COLUMN AP_PARENTESCOS.PARIENTE_ID IS
    'Pariente  asociado';

COMMENT ON COLUMN AP_PARENTESCOS.VINCULO IS
    'VINCULO entre el pasajero y el pariente (padre, madre, hijo, hermano, etc)';

ALTER TABLE AP_PARENTESCOS ADD CONSTRAINT PK_PARENTESCOS PRIMARY KEY ( PASAJERO_ID,
                                                                       PARIENTE_ID );

CREATE TABLE AP_PASAJEROS (
    PASAJERO_ID      NUMBER NOT NULL,
    TIPO_DOCUMENTO   CHAR(1 BYTE) NOT NULL,
    NRO_DOCUMENTO    VARCHAR2(12 BYTE) NOT NULL,
    NOMBRES          VARCHAR2(30 BYTE) NOT NULL,
    AP_PATERNO       VARCHAR2(30 BYTE) NOT NULL,
    AP_MATERNO       VARCHAR2(30 BYTE) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    SEXO             CHAR(1 BYTE) NOT NULL,
    CELULAR          CHAR(9 BYTE),
    EMAIL            VARCHAR2(30 BYTE),
    PAIS_ID          NUMBER NOT NULL
);

COMMENT ON COLUMN AP_PASAJEROS.PASAJERO_ID IS
    'Numero identificador del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.TIPO_DOCUMENTO IS
    'Tipo de documento puede ser:
- D: DNI
- P: Pasaporte';

COMMENT ON COLUMN AP_PASAJEROS.NRO_DOCUMENTO IS
    'El numero de documento puede tener 8 caracteres si es  DNI, pero 12 si es pasaporte';

COMMENT ON COLUMN AP_PASAJEROS.NOMBRES IS
    'NOMBRES del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.AP_PATERNO IS
    'Apellido paterno del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.AP_MATERNO IS
    'Apellido materno del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.FECHA_NACIMIENTO IS
    'Fecha de nacimiento del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.SEXO IS
    'SEXO del pasajero (como aparece en el DNI y pasaporte)
- M: Masculino
- F: Femenino';

COMMENT ON COLUMN AP_PASAJEROS.CELULAR IS
    'Numero de CELULAR del pasajero';

COMMENT ON COLUMN AP_PASAJEROS.EMAIL IS
    'Correo electronico (o EMAIL) del pasajero';

ALTER TABLE AP_PASAJEROS ADD CONSTRAINT PK_PASAJEROS PRIMARY KEY ( PASAJERO_ID );

CREATE TABLE AP_TIPOS_MANTENIMIENTO (
    TIPO_MANTENIMIENTO_ID NUMBER NOT NULL,
    DESCRIPCION           VARCHAR2(20 BYTE) NOT NULL
);

COMMENT ON COLUMN AP_TIPOS_MANTENIMIENTO.TIPO_MANTENIMIENTO_ID IS
    'Numero identificador del tipo de mantenimiento';

COMMENT ON COLUMN AP_TIPOS_MANTENIMIENTO.DESCRIPCION IS
    'Descripcion del mantenimiento:
- "Preventivo": para las fallas tecnicas
- "Correctivo": para los mantenimientos previstos';

ALTER TABLE AP_TIPOS_MANTENIMIENTO ADD CONSTRAINT PK_TIPOS_MANTENIMIENTO PRIMARY KEY ( TIPO_MANTENIMIENTO_ID );

CREATE TABLE AP_VUELOS (
    VUELO_ID              CHAR(6 BYTE) NOT NULL,
    FECHA_HORA_PARTIDA    DATE NOT NULL,
    FECHA_HORA_LLEGADA    DATE NOT NULL,
    AVION_ID              NUMBER NOT NULL,
    AEROPUERTO_PARTIDA_ID NUMBER NOT NULL,
    AEROPUERTO_LLEGADA_ID NUMBER NOT NULL
);

COMMENT ON COLUMN AP_VUELOS.VUELO_ID IS
    'Codigo alfanumerico identificador del vuelo (ej: LA2201, LA3203)';

COMMENT ON COLUMN AP_VUELOS.FECHA_HORA_PARTIDA IS
    'Fecha y hora de partida del vuelo';

COMMENT ON COLUMN AP_VUELOS.FECHA_HORA_LLEGADA IS
    'Fecha y hora de llegada del vuelo';

COMMENT ON COLUMN AP_VUELOS.AVION_ID IS
    'Avion al que esta asociado el vuelo';

COMMENT ON COLUMN AP_VUELOS.AEROPUERTO_PARTIDA_ID IS
    'Aeropuerto de partida';

COMMENT ON COLUMN AP_VUELOS.AEROPUERTO_LLEGADA_ID IS
    'Aeropuerto de llegada';

ALTER TABLE AP_VUELOS ADD CONSTRAINT PK_VUELOS PRIMARY KEY ( VUELO_ID );

ALTER TABLE AP_AEROPUERTOS
    ADD CONSTRAINT FK_AEROPUERTOS_CIUDADES FOREIGN KEY ( CIUDAD_ID,
                                                         PAIS_ID )
        REFERENCES AP_CIUDADES ( CIUDAD_ID,
                                 PAIS_ID );

ALTER TABLE AP_AVIONES
    ADD CONSTRAINT FK_AVIONES_MARCAS FOREIGN KEY ( MARCA_ID )
        REFERENCES AP_MARCAS ( MARCA_ID );

ALTER TABLE AP_BOLETOS
    ADD CONSTRAINT FK_BOLETOS_PASAJEROS FOREIGN KEY ( PASAJERO_ID )
        REFERENCES AP_PASAJEROS ( PASAJERO_ID );

ALTER TABLE AP_BOLETOS
    ADD CONSTRAINT FK_BOLETOS_VUELOS FOREIGN KEY ( VUELO_ID )
        REFERENCES AP_VUELOS ( VUELO_ID );

ALTER TABLE AP_CIUDADES
    ADD CONSTRAINT FK_CIUDADES_PAISES FOREIGN KEY ( PAIS_ID )
        REFERENCES AP_PAISES ( PAIS_ID );

ALTER TABLE AP_EMPLEADOS_VUELOS
    ADD CONSTRAINT FK_EMPLEADOS_VUELOS_VUELOS FOREIGN KEY ( VUELO_ID )
        REFERENCES AP_VUELOS ( VUELO_ID );

ALTER TABLE AP_EQUIPAJES_BOLETOS
    ADD CONSTRAINT FK_EQUIPAJES_BOLETOS_BOLETOS FOREIGN KEY ( BOLETO_ID )
        REFERENCES AP_BOLETOS ( BOLETO_ID );

ALTER TABLE AP_EQUIPAJES_BOLETOS
    ADD CONSTRAINT FK_EQUIPAJES_BOLETOS_EQUIPAJE FOREIGN KEY ( TIPO_EQUIPAJE_ID )
        REFERENCES AP_EQUIPAJES ( TIPO_EQUIPAJE_ID );

ALTER TABLE AP_MANT_AVIONES
    ADD CONSTRAINT FK_MANT_AVIONES_AVIONES FOREIGN KEY ( AVION_ID )
        REFERENCES AP_AVIONES ( AVION_ID );

ALTER TABLE AP_MANT_AVIONES
    ADD CONSTRAINT FK_MANT_AVIONES_TIPOS FOREIGN KEY ( TIPO_MANTENIMIENTO_ID )
        REFERENCES AP_TIPOS_MANTENIMIENTO ( TIPO_MANTENIMIENTO_ID );

ALTER TABLE AP_PARENTESCOS
    ADD CONSTRAINT FK_PARENTESCOS_PARIENTES FOREIGN KEY ( PARIENTE_ID )
        REFERENCES AP_PASAJEROS ( PASAJERO_ID );

ALTER TABLE AP_PARENTESCOS
    ADD CONSTRAINT FK_PARENTESCOS_PASAJEROS FOREIGN KEY ( PASAJERO_ID )
        REFERENCES AP_PASAJEROS ( PASAJERO_ID );

ALTER TABLE AP_PASAJEROS
    ADD CONSTRAINT FK_PASAJEROS_PAISES FOREIGN KEY ( PAIS_ID )
        REFERENCES AP_PAISES ( PAIS_ID );

ALTER TABLE AP_VUELOS
    ADD CONSTRAINT FK_VUELOS_AEROPUERTO_L FOREIGN KEY ( AEROPUERTO_LLEGADA_ID )
        REFERENCES AP_AEROPUERTOS ( AEROPUERTO_ID );

ALTER TABLE AP_VUELOS
    ADD CONSTRAINT FK_VUELOS_AEROPUERTO_P FOREIGN KEY ( AEROPUERTO_PARTIDA_ID )
        REFERENCES AP_AEROPUERTOS ( AEROPUERTO_ID );

ALTER TABLE AP_VUELOS
    ADD CONSTRAINT FK_VUELOS_AVIONES FOREIGN KEY ( AVION_ID )
        REFERENCES AP_AVIONES ( AVION_ID );
