-- Inserción de los mismos clientes usando el sequence
INSERT INTO L3_CLIENTES (CLIENTE_ID, TIPO_CLIENTE_ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, CODIGO_PUCP)
VALUES (seq_clientes.NEXTVAL, 1, 'Roberto', 'Gómez', 'rgomez@pucp.edu.pe', '999888777', '20240301');

INSERT INTO L3_CLIENTES (CLIENTE_ID, TIPO_CLIENTE_ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, CODIGO_PUCP)
VALUES (seq_clientes.NEXTVAL, 2, 'Patricia', 'Luna', 'pluna@pucp.edu.pe', '999888666', 'D0078901');

INSERT INTO L3_CLIENTES (CLIENTE_ID, TIPO_CLIENTE_ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, CODIGO_PUCP)
VALUES (seq_clientes.NEXTVAL, 1, 'Diego', 'Martínez', 'dmartinez@pucp.edu.pe', '999888555', '20240302');

INSERT INTO L3_CLIENTES (CLIENTE_ID, TIPO_CLIENTE_ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, CODIGO_PUCP)
VALUES (seq_clientes.NEXTVAL, 3, 'Carolina', 'Paz', 'cpaz@pucp.edu.pe', '999888444', 'A0089012');

INSERT INTO L3_CLIENTES (CLIENTE_ID, TIPO_CLIENTE_ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, CODIGO_PUCP)
VALUES (seq_clientes.NEXTVAL, 4, 'Fernando', 'Ríos', 'frios@gmail.com', '999888333', NULL);