-- 2025-0:

-- PREGUNTA 1:
-- A) SUGERENCIA

-- B)
-- El nombre de la tabla "SUGERENCIA":
-- TABLA
-- MODULO_ENTIDAD
-- L3_SUGERENCIA

-- El nombre del campo ID:
-- COLUMNA
-- ENTIDAD_ID
-- SUGERENCIA_ID

-- Nombres de campos con prefijo L3_:
-- COLUMNA
-- No llevan prefijos
-- TIPO_SUGERENCIA y FECHA_SUGERENCIA

-- C)

ALTER TABLE SUGERENCIA RENAME TO L3_SUGERENCIA;

ALTER TABLE L3_SUGERENCIA RENAME COLUMN ID TO SUGERENCIA_ID;
ALTER TABLE L3_SUGERENCIA RENAME COLUMN L3_FECHA_SUGERENCIA TO FECHA_SUGERENCIA;
ALTER TABLE L3_SUGERENCIA RENAME COLUMN L3_TIPO_SUGERENCIA TO TIPO_SUGERENCIA;

-- PREGUNTA 2:

-- A)
-- AGREGAR LA FECHA DESDE LA CUAL ESTÁ VIGENTE EL PRECIO ACTUAL
-- AGREGAR EL USUARIO QUIEN REALIZO LA ULTIMA MODIFICACION
-- AGREGAR LA FECHA EN QUE SE REALIZÓ LA ULTIMA MODIFICACION

-- B)

ALTER TABLE L3_PRODUCTOS
ADD (
    PRECIO_VIGENTE_DESDE    DATE DEFAULT SYSDATE,
    ULTIMO_USUARIO_MODIF     VARCHAR(100),
    ULTIMA_FECHA_MODIF      DATE DEFAULT SYSDATE
);

-- C)

CREATE TABLE L3_HISTORICO_PRECIOS(
    HISTORICO_ID    NUMBER NOT NULL,
    PRODUCTO_ID     NUMBER NOT NULL,
    PRECIO_ANTERIOR NUMBER(10,2) NOT NULL,
    PRECIO_NUEVO    NUMBER(10,2) NOT NULL,
    FECHA_INICIO_VIGENCIA DATE NOT NULL,
    FECHA_FIN_VIGENCIA    DATE NOT NULL,
    MOTIVO_CAMBIO   VARCHAR2(100) NOT NULL,
    USUARIO_REGISTRO VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_HISTORICO_PRECIOS PRIMARY KEY (HISTORICO_ID),
    CONSTRAINT FK_HISTORICO_PRODUCTOS FOREIGN KEY (PRODUCTO_ID)
    REFERENCES L3_PRODUCTOS(PRODUCTO_ID)
);

-- PREGUNTA 3:

-- PREGUNTA 4:

-- A)

SELECT
P.CODIGO_PRODUCTO,
P.NOMBRE AS NOMBRE_LIBRO,
L.ISBN,
E.NOMBRE AS EDITORIAL,
E.PAIS_ORIGEN,
E.CONTACTO_NOMBRE
FROM L3_PRODUCTOS P, L3_LIBROS L,L3_EDITORIALES E
WHERE P.PRODUCTO_ID = L.PRODUCTO_ID
AND P.EDITORIAL_ID = E.EDITORIAL_ID
AND P.ESTADO = 'ACTIVO'
AND P.PRECIO_BASE > 100
ORDER BY P.NOMBRE;

-- B)

SELECT PE.PEDIDO_ESPECIAL_ID,
PE.FECHA_SOLICITUD,
PE.ESTADO,
C.NOMBRE||' '|| C.APELLIDO AS NOMBRE_COMPLETO,
C.EMAIL,
C.TELEFONO
FROM L3_PEDIDOS_ESPECIALES PE, L3_CLIENTES C
WHERE C.CLIENTE_ID = PE.CLIENTE_ID
AND TO_CHAR(PE.FECHA_SOLICITUD,'YYYY') = '2024'
AND PE.MONTO_ADELANTADO >200
ORDER BY PE.FECHA_SOLICITUD;

