BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOLETAS_MEDICAMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOLETAS_SERVICIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOLETAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECETAS_MEDICAMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECETAS_MEDICAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ATENCIONES_MEDICAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE HORARIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SERVICIOS_MEDICOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICAMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERSONALES_MEDICOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACIENTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDADES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITAS_MEDICAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESULTADOS_LABORATORIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVENTARIO_MEDICAMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERTAS_MEDICAMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTAS_MEDICAMENTOS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

