CREATE TABLE ALERTAS_MEDICAMENTOS (
    ALERTA_ID      NUMBER NOT NULL,
    MEDICAMENTO_ID NUMBER NOT NULL,
    TIPO_ALERTA    VARCHAR2(50 BYTE) NOT NULL,
    MENSAJE        VARCHAR2(500 BYTE) NOT NULL,
    FECHA_ALERTA   DATE NOT NULL
);

COMMENT ON COLUMN ALERTAS_MEDICAMENTOS.ALERTA_ID IS
    'IDENTIFICADOR DE LA ALERTA.';

COMMENT ON COLUMN ALERTAS_MEDICAMENTOS.MEDICAMENTO_ID IS
    'IDENTIFICADOR DEL MEDICAMENTO.';

COMMENT ON COLUMN ALERTAS_MEDICAMENTOS.TIPO_ALERTA IS
    'TIPO DE ALERTA.';

COMMENT ON COLUMN ALERTAS_MEDICAMENTOS.MENSAJE IS
    'MENSAJE DE LA ALERTA.';

COMMENT ON COLUMN ALERTAS_MEDICAMENTOS.FECHA_ALERTA IS
    'FECHA DE LA ALERTA.';

ALTER TABLE ALERTAS_MEDICAMENTOS ADD CONSTRAINT ALERTAS_MEDICAMENTOS_PK PRIMARY KEY ( ALERTA_ID );

CREATE TABLE ATENCIONES_MEDICAS (
    ATENCION_ID  NUMBER NOT NULL,
    PACIENTE_ID  NUMBER NOT NULL,
    PERSONAL_ID  NUMBER NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    HORA_INICIO  DATE,
    HORA_FIN     DATE,
    DIAGNOSTICO  CLOB
);

ALTER TABLE ATENCIONES_MEDICAS ADD CONSTRAINT ATENCIONES_MEDICAS_PK PRIMARY KEY ( ATENCION_ID );

CREATE TABLE BOLETAS (
    BOLETA_ID     NUMBER NOT NULL,
    NRO_SERIE     VARCHAR2(20 BYTE) NOT NULL,
    PACIENTE_ID   NUMBER NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    MONTO_TOTAL   NUMBER(10, 2),
    METODO_PAGO   VARCHAR2(50 BYTE) NOT NULL
);

COMMENT ON COLUMN BOLETAS.BOLETA_ID IS
    'IDENTIFICADOR UNICO DE LA BOLETA DE PAGO.';

COMMENT ON COLUMN BOLETAS.NRO_SERIE IS
    'NUMERO DE SERIE DE LA BOLETA.';

COMMENT ON COLUMN BOLETAS.PACIENTE_ID IS
    'PACIENTE ASOCIADO A LA BOLETA.';

COMMENT ON COLUMN BOLETAS.FECHA_EMISION IS
    'FECHA EN QUE SE EMITIO LA BOLETA';

COMMENT ON COLUMN BOLETAS.MONTO_TOTAL IS
    'MONTO TOTAL FACTURADO.';

COMMENT ON COLUMN BOLETAS.METODO_PAGO IS
    'METODO DE PAGO UTILIZADO (EFECTIVO, TARJETA, ETC.)';

ALTER TABLE BOLETAS ADD CONSTRAINT CH_MONTO_TOTAL CHECK ( MONTO_TOTAL > 0 );

ALTER TABLE BOLETAS ADD CONSTRAINT BOLETAS_PK PRIMARY KEY ( BOLETA_ID );

ALTER TABLE BOLETAS ADD CONSTRAINT INDEX_1 UNIQUE ( NRO_SERIE );

CREATE TABLE BOLETAS_MEDICAMENTOS (
    BOLETA_ID       NUMBER NOT NULL,
    MEDICAMENTO_ID  NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10, 2) NOT NULL,
    CANTIDAD        NUMBER NOT NULL,
        SUBTOTAL        NUMBER(10, 2) AS ( PRECIO_UNITARIO * CANTIDAD ) VIRTUAL
);

ALTER TABLE BOLETAS_MEDICAMENTOS ADD CONSTRAINT PK_BOLETA_MEDICAMENTO PRIMARY KEY ( BOLETA_ID,
                                                                                    MEDICAMENTO_ID );

CREATE TABLE BOLETAS_SERVICIOS (
    BOLETA_ID       NUMBER NOT NULL,
    SERVICIO_ID     NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10, 2) NOT NULL,
    CANTIDAD        NUMBER NOT NULL,
        SUBTOTAL        NUMBER(10, 2) AS ( PRECIO_UNITARIO * CANTIDAD ) VIRTUAL
);

ALTER TABLE BOLETAS_SERVICIOS ADD CONSTRAINT PK_BOLETA_SERVICIO PRIMARY KEY ( BOLETA_ID,
                                                                              SERVICIO_ID );

CREATE TABLE CITAS_MEDICAS (
    CITA_ID     NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    PERSONAL_ID NUMBER NOT NULL,
    FECHA_CITA  DATE NOT NULL,
    HORA_CITA   DATE NOT NULL,
    ESTADO      VARCHAR2(20 BYTE) DEFAULT 'PROGRAMADA'
);

ALTER TABLE CITAS_MEDICAS ADD CONSTRAINT CITAS_MEDICAS_PK PRIMARY KEY ( CITA_ID );

CREATE TABLE ESPECIALIDADES (
    ESPECIALIDAD_ID NUMBER NOT NULL,
    DENOMINACION    VARCHAR2(100 BYTE) NOT NULL
);

ALTER TABLE ESPECIALIDADES ADD CONSTRAINT ESPECIALIDADES_PK PRIMARY KEY ( ESPECIALIDAD_ID );

CREATE TABLE HORARIOS (
    HORARIO_ID  NUMBER NOT NULL,
    PERSONAL_ID NUMBER NOT NULL,
    HORA_INICIO DATE NOT NULL,
    HORA_FIN    DATE NOT NULL
);

ALTER TABLE HORARIOS ADD CONSTRAINT HORARIOS_PK PRIMARY KEY ( HORARIO_ID );

CREATE TABLE INVENTARIO_MEDICAMENTOS (
    INVENTARIO_ID  NUMBER NOT NULL,
    MEDICAMENTO_ID NUMBER NOT NULL,
    UBICACION      VARCHAR2(100 BYTE) NOT NULL,
    CANTIDAD       NUMBER
);

ALTER TABLE INVENTARIO_MEDICAMENTOS ADD CONSTRAINT INVENTARIO_MEDICAMENTOS_PK PRIMARY KEY ( INVENTARIO_ID );

CREATE TABLE MEDICAMENTOS (
    MEDICAMENTO_ID    NUMBER NOT NULL,
    DENOMINACION      VARCHAR2(100 BYTE) NOT NULL,
    UNIDAD_DOSIS      VARCHAR2(50 BYTE) NOT NULL,
    DISPONIBLE_EN     VARCHAR2(100 BYTE),
    LOTE              VARCHAR2(50 BYTE),
    FECHA_VENCIMIENTO DATE,
    PRESENTACION      VARCHAR2(50 BYTE),
    ESTADO            VARCHAR2(20 BYTE)
);

COMMENT ON COLUMN MEDICAMENTOS.LOTE IS
    'IDENTIFICADOR DEL LOTE DE FABRICACION';

COMMENT ON COLUMN MEDICAMENTOS.FECHA_VENCIMIENTO IS
    'FECHA LIMITE DE USO DEL MEDICAMENTO';

COMMENT ON COLUMN MEDICAMENTOS.PRESENTACION IS
    'FORMATO FISICO DEL MEDICAMENTO';

COMMENT ON COLUMN MEDICAMENTOS.ESTADO IS
    'ESTADO DEL MEDICAMENTO: VIGENTE, VENCIDO O POR VENCER.';

ALTER TABLE MEDICAMENTOS ADD CONSTRAINT MEDICAMENTOS_PK PRIMARY KEY ( MEDICAMENTO_ID );

CREATE TABLE PACIENTES (
    PACIENTE_ID       NUMBER NOT NULL,
    NOMBRE            VARCHAR2(80 BYTE) NOT NULL,
    PRIMER_APELLIDO   VARCHAR2(50 BYTE) NOT NULL,
    TIPO_DOCUMENTO    VARCHAR2(20 BYTE) NOT NULL,
    NRO_DOCUMENTO     VARCHAR2(15 BYTE) NOT NULL,
    FECHA_NACIMIENTO  DATE NOT NULL,
    SEXO              CHAR(1 BYTE) NOT NULL,
    SEGUNDO_APELLIDO  VARCHAR2(50 BYTE),
    USUARIO_CREACION  NUMBER NOT NULL,
    FECHA_CREACION    DATE NOT NULL,
    USUARIO_ULT_MODIF NUMBER NOT NULL,
    FECHA_ULT_MODIF   DATE NOT NULL
);

COMMENT ON COLUMN PACIENTES.USUARIO_CREACION IS
    'IDENTIFICADOR DEL USUARIO QUE CREO EL REGISTRO';

COMMENT ON COLUMN PACIENTES.FECHA_CREACION IS
    'FECHA EN QUE SE CREO EL REGISTRO';

COMMENT ON COLUMN PACIENTES.USUARIO_ULT_MODIF IS
    'IDENTIFICADOR DEL USUARIO QUE MODIFICO POR ULTIMA VEZ EL REGISTRO';

COMMENT ON COLUMN PACIENTES.FECHA_ULT_MODIF IS
    'FECHA DE LA ULTIMA MODIFICACION DEL REGISTRO';

ALTER TABLE PACIENTES
    ADD CONSTRAINT CH_SEXO CHECK ( SEXO IN ( 'M', 'F' ) );

ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_PK PRIMARY KEY ( PACIENTE_ID );

ALTER TABLE PACIENTES ADD CONSTRAINT INDEX_1V1 UNIQUE ( NRO_DOCUMENTO );

CREATE TABLE PERSONALES_MEDICOS (
    PERSONAL_ID      NUMBER NOT NULL,
    NOMBRE           VARCHAR2(100 BYTE) NOT NULL,
    APELLIDOS        VARCHAR2(100 BYTE) NOT NULL,
    TIPO_DOCUMENTO   VARCHAR2(20 BYTE) NOT NULL,
    NRO_DOCUMENTO    VARCHAR2(20 BYTE) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    SEXO             CHAR(1 BYTE) NOT NULL,
    TIPO_PERSONAL    VARCHAR2(50 BYTE) NOT NULL,
    ROL              VARCHAR2(50 BYTE) NOT NULL,
    ESPECIALIDAD_ID  NUMBER NOT NULL
);

ALTER TABLE PERSONALES_MEDICOS ADD CONSTRAINT PERSONALES_MEDICOS_PK PRIMARY KEY ( PERSONAL_ID );

ALTER TABLE PERSONALES_MEDICOS ADD CONSTRAINT INDEX_1V2 UNIQUE ( NRO_DOCUMENTO );

CREATE TABLE RECETAS_MEDICAMENTOS (
    RECETA_ID          NUMBER NOT NULL,
    MEDICAMENTO_ID     NUMBER NOT NULL,
    CANTIDAD_DOSIS     NUMBER NOT NULL,
    FRECUENCIA         NUMBER(6, 2),
    DURACION           NUMBER(6, 2),
    VIA_ADMINISTRACION VARCHAR2(50 BYTE)
);

ALTER TABLE RECETAS_MEDICAMENTOS ADD CONSTRAINT CH_CANTIDAD_DOSIS CHECK ( CANTIDAD_DOSIS > 0 );

ALTER TABLE RECETAS_MEDICAMENTOS ADD CONSTRAINT PK_RECETA_MEDICAMENTO PRIMARY KEY ( RECETA_ID,
                                                                                    MEDICAMENTO_ID );

CREATE TABLE RECETAS_MEDICAS (
    RECETA_ID     NUMBER NOT NULL,
    ATENCION_ID   NUMBER NOT NULL,
    FECHA_EMISION DATE NOT NULL
);

ALTER TABLE RECETAS_MEDICAS ADD CONSTRAINT RECETAS_MEDICAS_PK PRIMARY KEY ( RECETA_ID );

CREATE TABLE RESULTADOS_LABORATORIO (
    RESULTADO_ID    NUMBER NOT NULL,
    ATENCION_ID     NUMBER NOT NULL,
    TIPO_PRUEBA     VARCHAR2(100 BYTE) NOT NULL,
    FECHA_RESULTADO DATE NOT NULL,
    VALOR_RESULTADO VARCHAR2(100 BYTE)
);

ALTER TABLE RESULTADOS_LABORATORIO ADD CONSTRAINT RESULTADOS_LABORATORIO_PK PRIMARY KEY ( RESULTADO_ID );

CREATE TABLE SERVICIOS_MEDICOS (
    SERVICIO_ID     NUMBER NOT NULL,
    DENOMINACION    VARCHAR2(100 BYTE) NOT NULL,
    PRECIO          NUMBER(10, 2) NOT NULL,
    ESPECIALIDAD_ID NUMBER NOT NULL
);

ALTER TABLE SERVICIOS_MEDICOS ADD CONSTRAINT SERVICIOS_MEDICOS_PK PRIMARY KEY ( SERVICIO_ID );

ALTER TABLE ALERTAS_MEDICAMENTOS
    ADD CONSTRAINT FK_ALERTA_MED FOREIGN KEY ( MEDICAMENTO_ID )
        REFERENCES MEDICAMENTOS ( MEDICAMENTO_ID );

ALTER TABLE RESULTADOS_LABORATORIO
    ADD CONSTRAINT FK_ATENCION_ID FOREIGN KEY ( ATENCION_ID )
        REFERENCES ATENCIONES_MEDICAS ( ATENCION_ID );

ALTER TABLE ATENCIONES_MEDICAS
    ADD CONSTRAINT FK_ATENCION_PACIENTE FOREIGN KEY ( PACIENTE_ID )
        REFERENCES PACIENTES ( PACIENTE_ID );

ALTER TABLE ATENCIONES_MEDICAS
    ADD CONSTRAINT FK_ATENCION_PERSONAL FOREIGN KEY ( PERSONAL_ID )
        REFERENCES PERSONALES_MEDICOS ( PERSONAL_ID );

ALTER TABLE BOLETAS_MEDICAMENTOS
    ADD CONSTRAINT FK_BM_BOLETA FOREIGN KEY ( BOLETA_ID )
        REFERENCES BOLETAS ( BOLETA_ID );

ALTER TABLE BOLETAS_MEDICAMENTOS
    ADD CONSTRAINT FK_BM_MEDICAMENTO FOREIGN KEY ( MEDICAMENTO_ID )
        REFERENCES MEDICAMENTOS ( MEDICAMENTO_ID );

ALTER TABLE BOLETAS
    ADD CONSTRAINT FK_BOLETA_PACIENTE FOREIGN KEY ( PACIENTE_ID )
        REFERENCES PACIENTES ( PACIENTE_ID );

ALTER TABLE BOLETAS_SERVICIOS
    ADD CONSTRAINT FK_BS_BOLETA FOREIGN KEY ( BOLETA_ID )
        REFERENCES BOLETAS ( BOLETA_ID );

ALTER TABLE BOLETAS_SERVICIOS
    ADD CONSTRAINT FK_BS_SERVICIO FOREIGN KEY ( SERVICIO_ID )
        REFERENCES SERVICIOS_MEDICOS ( SERVICIO_ID );

ALTER TABLE HORARIOS
    ADD CONSTRAINT FK_HORARIO_PERSONAL FOREIGN KEY ( PERSONAL_ID )
        REFERENCES PERSONALES_MEDICOS ( PERSONAL_ID );

ALTER TABLE INVENTARIO_MEDICAMENTOS
    ADD CONSTRAINT FK_MEDICAMENTO_ID FOREIGN KEY ( MEDICAMENTO_ID )
        REFERENCES MEDICAMENTOS ( MEDICAMENTO_ID );

ALTER TABLE CITAS_MEDICAS
    ADD CONSTRAINT FK_PACIENTE_ID FOREIGN KEY ( PACIENTE_ID )
        REFERENCES PACIENTES ( PACIENTE_ID );

ALTER TABLE PERSONALES_MEDICOS
    ADD CONSTRAINT FK_PERSONAL_ESPECIALIDAD FOREIGN KEY ( ESPECIALIDAD_ID )
        REFERENCES ESPECIALIDADES ( ESPECIALIDAD_ID );

ALTER TABLE CITAS_MEDICAS
    ADD CONSTRAINT FK_PERSONAL_ID FOREIGN KEY ( PERSONAL_ID )
        REFERENCES PERSONALES_MEDICOS ( PERSONAL_ID );

ALTER TABLE RECETAS_MEDICAS
    ADD CONSTRAINT FK_RECETA_ATENCION FOREIGN KEY ( ATENCION_ID )
        REFERENCES ATENCIONES_MEDICAS ( ATENCION_ID );

ALTER TABLE RECETAS_MEDICAMENTOS
    ADD CONSTRAINT FK_RM_MEDICAMENTO FOREIGN KEY ( MEDICAMENTO_ID )
        REFERENCES MEDICAMENTOS ( MEDICAMENTO_ID );

ALTER TABLE RECETAS_MEDICAMENTOS
    ADD CONSTRAINT FK_RM_RECETA FOREIGN KEY ( RECETA_ID )
        REFERENCES RECETAS_MEDICAS ( RECETA_ID );

ALTER TABLE SERVICIOS_MEDICOS
    ADD CONSTRAINT FK_SERVICIO_ESPECIALIDAD FOREIGN KEY ( ESPECIALIDAD_ID )
        REFERENCES ESPECIALIDADES ( ESPECIALIDAD_ID );

