
/* ESPECIALIDADES */
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (1, 'Medicina General');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (2, 'Enfermería');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (3, 'Nutrición');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (4, 'Psicología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (5, 'Dermatología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (6, 'Cardiología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (7, 'Gastroenterología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (8, 'Neumología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (9, 'Neurología');
INSERT INTO ESPECIALIDADES (ESPECIALIDAD_ID, DENOMINACION) VALUES (10, 'Pediatría');
/* PERSONALES_MEDICOS */
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (101, 'Ana', 'Torres Valdez', 'DNI', '10013837', TO_DATE('1980-01-01','YYYY-MM-DD') + 101, 'M', 'Medico de atencion primaria', 'Medico General', 1);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (102, 'Luis', 'Ramos Quispe', 'DNI', '10013974', TO_DATE('1980-01-01','YYYY-MM-DD') + 102, 'F', 'Enfermero', 'Enfermeria', 2);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (103, 'Carla', 'Vega Salazar', 'DNI', '10014111', TO_DATE('1980-01-01','YYYY-MM-DD') + 103, 'M', 'Nutricionista', 'Nutricion', 3);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (104, 'Diego', 'Huamán Soto', 'DNI', '10014248', TO_DATE('1980-01-01','YYYY-MM-DD') + 104, 'F', 'Psicologo', 'Psicologia Clinica', 4);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (105, 'María', 'Gómez Rivas', 'DNI', '10014385', TO_DATE('1980-01-01','YYYY-MM-DD') + 105, 'M', 'Medico de atencion primaria', 'Medico General', 1);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (106, 'Jorge', 'Paredes Díaz', 'DNI', '10014522', TO_DATE('1980-01-01','YYYY-MM-DD') + 106, 'F', 'Enfermero', 'Enfermeria', 2);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (107, 'Elena', 'Luna Chávez', 'DNI', '10014659', TO_DATE('1980-01-01','YYYY-MM-DD') + 107, 'M', 'Nutricionista', 'Nutricion', 3);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (108, 'Gabriel', 'Mendoza Córdova', 'DNI', '10014796', TO_DATE('1980-01-01','YYYY-MM-DD') + 108, 'F', 'Psicologo', 'Psicologia Clinica', 4);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (109, 'Rosa', 'Salinas Flores', 'DNI', '10014933', TO_DATE('1980-01-01','YYYY-MM-DD') + 109, 'M', 'Medico de atencion primaria', 'Medico General', 1);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (110, 'Alfredo', 'Campos Lozano', 'DNI', '10015070', TO_DATE('1980-01-01','YYYY-MM-DD') + 110, 'F', 'Enfermero', 'Enfermeria', 2);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (111, 'Claudia', 'Zegarra Prado', 'DNI', '10015207', TO_DATE('1980-01-01','YYYY-MM-DD') + 111, 'M', 'Nutricionista', 'Nutricion', 3);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (112, 'Pablo', 'Núñez Cornejo', 'DNI', '10015344', TO_DATE('1980-01-01','YYYY-MM-DD') + 112, 'F', 'Psicologo', 'Psicologia Clinica', 4);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (113, 'Sofía', 'Ponce Hidalgo', 'DNI', '10015481', TO_DATE('1980-01-01','YYYY-MM-DD') + 113, 'M', 'Medico de atencion primaria', 'Medico General', 1);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (114, 'Hugo', 'Peralta Ibarra', 'DNI', '10015618', TO_DATE('1980-01-01','YYYY-MM-DD') + 114, 'F', 'Enfermero', 'Enfermeria', 2);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (115, 'Natalia', 'Rivas Castañeda', 'DNI', '10015755', TO_DATE('1980-01-01','YYYY-MM-DD') + 115, 'M', 'Nutricionista', 'Nutricion', 3);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (116, 'Ricardo', 'Valverde Yauri', 'DNI', '10015892', TO_DATE('1980-01-01','YYYY-MM-DD') + 116, 'F', 'Psicologo', 'Psicologia Clinica', 4);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (117, 'Paty', 'Caballero Gutiérrez', 'DNI', '10016029', TO_DATE('1980-01-01','YYYY-MM-DD') + 117, 'M', 'Medico de atencion primaria', 'Medico General', 1);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (118, 'Omar', 'Sifuentes León', 'DNI', '10016166', TO_DATE('1980-01-01','YYYY-MM-DD') + 118, 'F', 'Enfermero', 'Enfermeria', 2);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (119, 'Daniela', 'Mori Arista', 'DNI', '10016303', TO_DATE('1980-01-01','YYYY-MM-DD') + 119, 'M', 'Nutricionista', 'Nutricion', 3);
INSERT INTO PERSONALES_MEDICOS (PERSONAL_ID, NOMBRE, APELLIDOS, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO, TIPO_PERSONAL, ROL, ESPECIALIDAD_ID) VALUES (120, 'Gustavo', 'Reyna Prado', 'DNI', '10016440', TO_DATE('1980-01-01','YYYY-MM-DD') + 120, 'F', 'Psicologo', 'Psicologia Clinica', 4);

/* PACIENTES */
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (201, 'Juan', 'Pérez', 'CE', '0000100000', TO_DATE('1985-01-01','YYYY-MM-DD') + 0, 'M', 'López', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (202, 'María', 'Gómez', 'DNI', '40000321', TO_DATE('1985-01-01','YYYY-MM-DD') + 365, 'F', 'Ruiz', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (203, 'Carlos', 'Sánchez', 'DNI', '40000642', TO_DATE('1985-01-01','YYYY-MM-DD') + 730, 'M', 'Díaz', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (204, 'Lucía', 'Fernández', 'CE', '0000100003', TO_DATE('1985-01-01','YYYY-MM-DD') + 1095, 'F', 'Castro', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (205, 'Pedro', 'Ramírez', 'DNI', '40001284', TO_DATE('1985-01-01','YYYY-MM-DD') + 1460, 'M', 'García', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (206, 'Daniela', 'Torres', 'DNI', '40001605', TO_DATE('1985-01-01','YYYY-MM-DD') + 1825, 'F', 'Valdez', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (207, 'José', 'Flores', 'CE', '0000100006', TO_DATE('1985-01-01','YYYY-MM-DD') + 2190, 'M', 'Huamán', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (208, 'Carmen', 'Díaz', 'DNI', '40002247', TO_DATE('1985-01-01','YYYY-MM-DD') + 2555, 'F', 'Quispe', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (209, 'Alberto', 'Vargas', 'DNI', '40002568', TO_DATE('1985-01-01','YYYY-MM-DD') + 2920, 'M', 'Salinas', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (210, 'Patricia', 'Castro', 'CE', '0000100009', TO_DATE('1985-01-01','YYYY-MM-DD') + 3285, 'F', 'Campos', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (211, 'Miguel', 'Rojas', 'DNI', '40003210', TO_DATE('1985-01-01','YYYY-MM-DD') + 3650, 'M', 'Zegarra', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (212, 'Verónica', 'Mendoza', 'DNI', '40003531', TO_DATE('1985-01-01','YYYY-MM-DD') + 4015, 'F', 'Cornejo', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (213, 'Andrés', 'Jiménez', 'CE', '0000100012', TO_DATE('1985-01-01','YYYY-MM-DD') + 4380, 'M', 'Hidalgo', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (214, 'Ximena', 'Ruiz', 'DNI', '40004173', TO_DATE('1985-01-01','YYYY-MM-DD') + 4745, 'F', 'Ibarra', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (215, 'Raúl', 'Morales', 'DNI', '40004494', TO_DATE('1985-01-01','YYYY-MM-DD') + 5110, 'M', 'Castañeda', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (216, 'Diana', 'Herrera', 'CE', '0000100015', TO_DATE('1985-01-01','YYYY-MM-DD') + 5475, 'F', 'Prado', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (217, 'Héctor', 'Guerrero', 'DNI', '40005136', TO_DATE('1985-01-01','YYYY-MM-DD') + 5840, 'M', 'Lozano', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (218, 'Valeria', 'Cruz', 'DNI', '40005457', TO_DATE('1985-01-01','YYYY-MM-DD') + 6205, 'F', 'Córdova', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (219, 'Fernando', 'Chávez', 'CE', '0000100018', TO_DATE('1985-01-01','YYYY-MM-DD') + 6570, 'M', 'Rivas', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));
INSERT INTO PACIENTES (PACIENTE_ID, NOMBRE, PRIMER_APELLIDO, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_NACIMIENTO, SEXO,  SEGUNDO_APELLIDO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ULT_MODIF, FECHA_ULT_MODIF) VALUES (220, 'Paola', 'Salazar', 'DNI', '40006099', TO_DATE('1985-01-01','YYYY-MM-DD') + 6935, 'F', 'Flores', 1, TO_DATE('2025-05-10','YYYY-MM-DD'), 1, TO_DATE('2025-05-10','YYYY-MM-DD'));

/* SERVICIOS_MEDICOS */
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (301, 'Consulta Medicina General', 50.50, 1);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (302, 'Control Medicina General', 60.50, 1);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (303, 'Consulta Dermatología', 70.50, 5);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (304, 'Control Dermatología', 80.50, 5);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (305, 'Consulta Cardiología', 90.50, 6);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (306, 'Control Cardiología', 40.50, 6);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (307, 'Consulta Gastroenterología', 50.50, 7);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (308, 'Control Gastroenterología', 60.50, 7);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (309, 'Consulta Neumología', 70.50, 8);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (310, 'Control Neumología', 80.50, 8);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (311, 'Consulta Neurología', 90.50, 9);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (312, 'Control Neurología', 40.50, 9);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (313, 'Consulta Pediatría', 50.50, 10);
INSERT INTO SERVICIOS_MEDICOS (SERVICIO_ID, DENOMINACION, PRECIO, ESPECIALIDAD_ID) VALUES (314, 'Control Pediatría', 60.50, 10);

/* MEDICAMENTOS */
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (701, 'Loratadina 10 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-001', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (702, 'Paracetamol 500 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-002', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (703, 'Ibuprofeno 400 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-003', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (704, 'Amoxicilina 500 mg', 'cápsula', 'Farmacia MásSalud - Sede San Miguel', 'LOT-004', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Blister x12', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (705, 'Omeprazol 20 mg', 'cápsula', 'Farmacia MásSalud - Sede San Miguel', 'LOT-005', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Blister x14', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (706, 'Salbutamol 100 mcg', 'inhalador', 'Farmacia MásSalud - Sede San Miguel', 'LOT-006', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Inhalador 200 dosis', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (707, 'Metformina 850 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-007', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Blister x30', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (708, 'Atorvastatina 20 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-008', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Blister x30', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (709, 'Losartán 50 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-009', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Blister x30', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (710, 'Enalapril 10 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-010', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Blister x30', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (711, 'Cetirizina 10 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-011', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (712, 'Diclofenaco 50 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-012', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (713, 'Azitromicina 500 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-013', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Blister x3', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (714, 'Betametasona crema', 'crema', 'Farmacia MásSalud - Sede San Miguel', 'LOT-014', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Tubo 30g', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (715, 'Clotrimazol crema', 'crema', 'Farmacia MásSalud - Sede San Miguel', 'LOT-015', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Tubo 20g', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (716, 'Hidrocortisona crema', 'crema', 'Farmacia MásSalud - Sede San Miguel', 'LOT-016', TO_DATE('2026-05-12','YYYY-MM-DD'), 'Tubo 20g', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (717, 'Ranitidina 150 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-017', TO_DATE('2027-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');
INSERT INTO MEDICAMENTOS (MEDICAMENTO_ID, DENOMINACION, UNIDAD_DOSIS, DISPONIBLE_EN, LOTE, FECHA_VENCIMIENTO, PRESENTACION, ESTADO) VALUES (718, 'Naproxeno 500 mg', 'tableta', 'Farmacia MásSalud - Sede San Miguel', 'LOT-018', TO_DATE('2028-05-12','YYYY-MM-DD'), 'Blister x10', 'VIGENTE');



INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (801, 701, 'Almacén S1 - Estante 1', 20);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (802, 702, 'Almacén S2 - Estante 2', 21);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (803, 703, 'Almacén S3 - Estante 3', 22);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (804, 704, 'Almacén S1 - Estante 4', 23);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (805, 705, 'Almacén S2 - Estante 5', 24);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (806, 706, 'Almacén S3 - Estante 1', 25);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (807, 707, 'Almacén S1 - Estante 2', 26);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (808, 708, 'Almacén S2 - Estante 3', 27);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (809, 709, 'Almacén S3 - Estante 4', 28);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (810, 710, 'Almacén S1 - Estante 5', 29);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (811, 711, 'Almacén S2 - Estante 1', 30);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (812, 712, 'Almacén S3 - Estante 2', 31);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (813, 713, 'Almacén S1 - Estante 3', 32);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (814, 714, 'Almacén S2 - Estante 4', 33);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (815, 715, 'Almacén S3 - Estante 5', 34);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (816, 716, 'Almacén S1 - Estante 1', 35);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (817, 717, 'Almacén S2 - Estante 2', 36);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (818, 718, 'Almacén S3 - Estante 3', 37);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (819, 717, 'Almacén S1 - Estante 4', 38);
INSERT INTO INVENTARIO_MEDICAMENTOS (INVENTARIO_ID, MEDICAMENTO_ID, UBICACION, CANTIDAD) VALUES (820, 718, 'Almacén S2 - Estante 5', 39);

/* HORARIOS */
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (901, 101, TO_DATE('08:00','HH24:MI'), TO_DATE('09:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (902, 102, TO_DATE('09:00','HH24:MI'), TO_DATE('10:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (903, 103, TO_DATE('10:00','HH24:MI'), TO_DATE('11:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (904, 104, TO_DATE('11:00','HH24:MI'), TO_DATE('12:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (905, 105, TO_DATE('12:00','HH24:MI'), TO_DATE('13:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (906, 106, TO_DATE('13:00','HH24:MI'), TO_DATE('14:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (907, 107, TO_DATE('14:00','HH24:MI'), TO_DATE('15:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (908, 108, TO_DATE('15:00','HH24:MI'), TO_DATE('16:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (909, 109, TO_DATE('08:00','HH24:MI'), TO_DATE('09:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (910, 110, TO_DATE('09:00','HH24:MI'), TO_DATE('10:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (911, 111, TO_DATE('10:00','HH24:MI'), TO_DATE('11:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (912, 112, TO_DATE('11:00','HH24:MI'), TO_DATE('12:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (913, 113, TO_DATE('12:00','HH24:MI'), TO_DATE('13:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (914, 114, TO_DATE('13:00','HH24:MI'), TO_DATE('14:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (915, 115, TO_DATE('14:00','HH24:MI'), TO_DATE('15:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (916, 116, TO_DATE('15:00','HH24:MI'), TO_DATE('16:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (917, 117, TO_DATE('08:00','HH24:MI'), TO_DATE('09:00','HH24:MI'));
INSERT INTO HORARIOS (HORARIO_ID, PERSONAL_ID, HORA_INICIO, HORA_FIN) VALUES (918, 118, TO_DATE('09:00','HH24:MI'), TO_DATE('10:00','HH24:MI'));

/* ATENCIONES_MEDICAS */
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (501, 201, 101, TO_DATE('12/09/2025','DD/MM/YYYY'),TO_DATE('08:00','HH24:MI'), TO_DATE('08:30','HH24:MI'), 'Gripe viral sin complicaciones');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (502, 202, 102, TO_DATE('13/09/2025','DD/MM/YYYY'),TO_DATE('09:00','HH24:MI'), TO_DATE('09:45','HH24:MI'), 'Hipertensión arterial controlada');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (503, 203, 103, TO_DATE('14/09/2025','DD/MM/YYYY'),TO_DATE('10:00','HH24:MI'), TO_DATE('10:40','HH24:MI'), 'Ansiedad generalizada leve');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (504, 204, 104, TO_DATE('15/09/2025','DD/MM/YYYY'),TO_DATE('11:00','HH24:MI'), TO_DATE('11:50','HH24:MI'), 'Sobrepeso por malos hábitos alimenticios');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (505, 205, 105, TO_DATE('16/09/2025','DD/MM/YYYY'),TO_DATE('08:30','HH24:MI'), TO_DATE('09:10','HH24:MI'), 'Migraña recurrente');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (506, 206, 106, TO_DATE('16/09/2025','DD/MM/YYYY'),TO_DATE('09:30','HH24:MI'), TO_DATE('10:15','HH24:MI'), 'Trastorno depresivo moderado');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (507, 207, 107, TO_DATE('17/09/2025','DD/MM/YYYY'),TO_DATE('10:30','HH24:MI'), TO_DATE('11:00','HH24:MI'), 'Diabetes mellitus tipo 2 en control');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (508, 208, 108, TO_DATE('17/09/2025','DD/MM/YYYY'),TO_DATE('11:15','HH24:MI'), TO_DATE('11:50','HH24:MI'), 'Obesidad grado I');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (509, 209, 109, TO_DATE('18/09/2025','DD/MM/YYYY'),TO_DATE('08:45','HH24:MI'), TO_DATE('09:30','HH24:MI'), 'Estrés laboral crónico');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (510, 210, 110, TO_DATE('18/09/2025','DD/MM/YYYY'),TO_DATE('09:45','HH24:MI'), TO_DATE('10:20','HH24:MI'), 'Hipotiroidismo subclínico');
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (511, 211, 111, TO_DATE('2025-10-05','YYYY-MM-DD'), TO_DATE('13:00','HH24:MI'), TO_DATE('13:15','HH24:MI'), TO_CLOB('Consejería nutricional por sobrepeso (IMC 28); plan hipocalórico y control en 4 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (512, 212, 112, TO_DATE('2025-10-05','YYYY-MM-DD'), TO_DATE('14:00','HH24:MI'), TO_DATE('14:30','HH24:MI'), TO_CLOB('Ansiedad leve; psicoeducación, técnicas de respiración y seguimiento en 2 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (513, 213, 113, TO_DATE('2025-10-06','YYYY-MM-DD'), TO_DATE('09:00','HH24:MI'), TO_DATE('09:15','HH24:MI'), TO_CLOB('Infección respiratoria alta no complicada; manejo sintomático con paracetamol y reposo.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (514, 214, 115, TO_DATE('2025-10-06','YYYY-MM-DD'), TO_DATE('10:00','HH24:MI'), TO_DATE('10:30','HH24:MI'), TO_CLOB('Consejería nutricional por sobrepeso (IMC 28); plan hipocalórico y control en 4 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (515, 215, 115, TO_DATE('2025-10-06','YYYY-MM-DD'), TO_DATE('11:00','HH24:MI'), TO_DATE('11:15','HH24:MI'), TO_CLOB('Consejería nutricional por sobrepeso (IMC 28); plan hipocalórico y control en 4 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (516, 216, 116, TO_DATE('2025-10-07','YYYY-MM-DD'), TO_DATE('12:00','HH24:MI'), TO_DATE('12:30','HH24:MI'), TO_CLOB('Ansiedad leve; psicoeducación, técnicas de respiración y seguimiento en 2 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (517, 217, 117, TO_DATE('2025-10-07','YYYY-MM-DD'), TO_DATE('13:00','HH24:MI'), TO_DATE('13:15','HH24:MI'), TO_CLOB('Infección respiratoria alta no complicada; manejo sintomático con paracetamol y reposo.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (518, 218, 119, TO_DATE('2025-10-07','YYYY-MM-DD'), TO_DATE('14:00','HH24:MI'), TO_DATE('14:30','HH24:MI'), TO_CLOB('Consejería nutricional por sobrepeso (IMC 28); plan hipocalórico y control en 4 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (519, 219, 119, TO_DATE('2025-10-08','YYYY-MM-DD'), TO_DATE('09:00','HH24:MI'), TO_DATE('09:15','HH24:MI'), TO_CLOB('Consejería nutricional por sobrepeso (IMC 28); plan hipocalórico y control en 4 semanas.'));
INSERT INTO ATENCIONES_MEDICAS (ATENCION_ID, PACIENTE_ID, PERSONAL_ID, FECHA_INICIO, HORA_INICIO, HORA_FIN, DIAGNOSTICO) VALUES (520, 220, 120, TO_DATE('2025-10-08','YYYY-MM-DD'), TO_DATE('10:00','HH24:MI'), TO_DATE('10:30','HH24:MI'), TO_CLOB('Ansiedad leve; psicoeducación, técnicas de respiración y seguimiento en 2 semanas.'));

/* CITAS_MEDICAS */
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (951, 201, 101, TO_DATE('2025-05-12','YYYY-MM-DD'), TO_DATE('08:00','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (952, 202, 102, TO_DATE('2025-05-12','YYYY-MM-DD'), TO_DATE('09:30','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (953, 203, 103, TO_DATE('2025-05-13','YYYY-MM-DD'), TO_DATE('10:00','HH24:MI'), 'Cancelada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (954, 204, 104, TO_DATE('2025-05-13','YYYY-MM-DD'), TO_DATE('11:30','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (955, 205, 105, TO_DATE('2025-05-14','YYYY-MM-DD'), TO_DATE('12:00','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (956, 206, 106, TO_DATE('2025-05-14','YYYY-MM-DD'), TO_DATE('13:30','HH24:MI'), 'Cancelada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (957, 207, 107, TO_DATE('2025-05-15','YYYY-MM-DD'), TO_DATE('14:00','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (958, 208, 108, TO_DATE('2025-05-15','YYYY-MM-DD'), TO_DATE('15:30','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (959, 209, 109, TO_DATE('2025-05-16','YYYY-MM-DD'), TO_DATE('16:00','HH24:MI'), 'Cancelada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (960, 210, 110, TO_DATE('2025-05-16','YYYY-MM-DD'), TO_DATE('08:30','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (961, 211, 111, TO_DATE('2025-05-17','YYYY-MM-DD'), TO_DATE('09:00','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (962, 212, 112, TO_DATE('2025-05-17','YYYY-MM-DD'), TO_DATE('10:30','HH24:MI'), 'Cancelada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (963, 213, 113, TO_DATE('2025-05-18','YYYY-MM-DD'), TO_DATE('11:00','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (964, 214, 114, TO_DATE('2025-05-18','YYYY-MM-DD'), TO_DATE('12:30','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (965, 215, 115, TO_DATE('2025-05-19','YYYY-MM-DD'), TO_DATE('13:00','HH24:MI'), 'Cancelada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (966, 216, 116, TO_DATE('2025-05-19','YYYY-MM-DD'), TO_DATE('14:30','HH24:MI'), 'Programada');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (967, 217, 117, TO_DATE('2025-05-20','YYYY-MM-DD'), TO_DATE('15:00','HH24:MI'), 'Atendida');
INSERT INTO CITAS_MEDICAS (CITA_ID, PACIENTE_ID, PERSONAL_ID, FECHA_CITA, HORA_CITA, ESTADO) VALUES (968, 218, 118, TO_DATE('2025-05-20','YYYY-MM-DD'), TO_DATE('16:30','HH24:MI'), 'Cancelada');


INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (601, 501, TO_DATE('2025-05-12','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (602, 502, TO_DATE('2025-05-12','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (603, 503, TO_DATE('2025-05-12','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (604, 504, TO_DATE('2025-05-13','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (605, 505, TO_DATE('2025-05-13','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (606, 506, TO_DATE('2025-05-13','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (607, 507, TO_DATE('2025-05-14','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (608, 508, TO_DATE('2025-05-14','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (609, 509, TO_DATE('2025-05-14','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (610, 510, TO_DATE('2025-05-15','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (611, 511, TO_DATE('2025-05-15','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (612, 512, TO_DATE('2025-05-15','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (613, 513, TO_DATE('2025-05-16','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (614, 514, TO_DATE('2025-05-16','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (615, 515, TO_DATE('2025-05-16','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (616, 516, TO_DATE('2025-05-17','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (617, 517, TO_DATE('2025-05-17','YYYY-MM-DD'));
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (618, 518, TO_DATE('2025-05-17','YYYY-MM-DD'));


INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (601, 702, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (601, 713, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (602, 715, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (603, 709, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (603, 710, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (604, 715, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (605, 711, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (606, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (607, 707, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (608, 703, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (608, 718, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (609, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (612, 703, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (612, 712, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (613, 702, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (613, 713, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (614, 708, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (615, 715, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (616, 703, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (616, 712, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (617, 714, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (617, 716, 2, 2.0, 6, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (618, 708, 1, 3.0, 5, 'Oral');


INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1001, 501, 'Hemograma', TO_DATE('2025-05-12','YYYY-MM-DD'), '4.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1002, 502, 'Perfil lipídico', TO_DATE('2025-05-12','YYYY-MM-DD'), '159.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1003, 503, 'Glucosa', TO_DATE('2025-05-12','YYYY-MM-DD'), '78.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1004, 504, 'TSH', TO_DATE('2025-05-12','YYYY-MM-DD'), '1.48');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1005, 505, 'PCR', TO_DATE('2025-05-13','YYYY-MM-DD'), '2.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1006, 506, 'Vitamina D', TO_DATE('2025-05-13','YYYY-MM-DD'), '35.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1007, 507, 'Función Hepática', TO_DATE('2025-05-13','YYYY-MM-DD'), '28.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1008, 508, 'Función Renal', TO_DATE('2025-05-13','YYYY-MM-DD'), '1.02');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1009, 509, 'Hemograma', TO_DATE('2025-05-14','YYYY-MM-DD'), '9.6');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1010, 510, 'Perfil lipídico', TO_DATE('2025-05-14','YYYY-MM-DD'), '231.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1011, 511, 'Glucosa', TO_DATE('2025-05-14','YYYY-MM-DD'), '70.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1012, 512, 'TSH', TO_DATE('2025-05-14','YYYY-MM-DD'), '0.76');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1013, 513, 'PCR', TO_DATE('2025-05-15','YYYY-MM-DD'), '1.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1014, 514, 'Vitamina D', TO_DATE('2025-05-15','YYYY-MM-DD'), '29.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1015, 515, 'Función Hepática', TO_DATE('2025-05-15','YYYY-MM-DD'), '22.0');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1016, 516, 'Función Renal', TO_DATE('2025-05-15','YYYY-MM-DD'), '0.9');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1017, 517, 'Hemograma', TO_DATE('2025-05-16','YYYY-MM-DD'), '8.2');
INSERT INTO RESULTADOS_LABORATORIO (RESULTADO_ID, ATENCION_ID, TIPO_PRUEBA, FECHA_RESULTADO, VALOR_RESULTADO) VALUES (1018, 518, 'Perfil lipídico', TO_DATE('2025-05-16','YYYY-MM-DD'), '213.0');

/* BOLETAS*/
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (401, 'BMS-0001', 201, TO_DATE('2025-05-12','YYYY-MM-DD'), 69.50, 'Yape');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (402, 'BMS-0002', 202, TO_DATE('2025-05-12','YYYY-MM-DD'), 60.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (403, 'BMS-0003', 203, TO_DATE('2025-05-12','YYYY-MM-DD'), 109.50, 'Efectivo');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (404, 'BMS-0004', 204, TO_DATE('2025-05-12','YYYY-MM-DD'), 80.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (405, 'BMS-0005', 205, TO_DATE('2025-05-13','YYYY-MM-DD'), 107.00, 'Yape');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (406, 'BMS-0006', 206, TO_DATE('2025-05-13','YYYY-MM-DD'), 40.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (407, 'BMS-0007', 207, TO_DATE('2025-05-13','YYYY-MM-DD'), 88.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (408, 'BMS-0008', 208, TO_DATE('2025-05-13','YYYY-MM-DD'), 60.50, 'Plin');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (409, 'BMS-0009', 209, TO_DATE('2025-05-14','YYYY-MM-DD'), 135.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (410, 'BMS-0010', 210, TO_DATE('2025-05-14','YYYY-MM-DD'), 80.50, 'Yape');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (411, 'BMS-0011', 211, TO_DATE('2025-05-14','YYYY-MM-DD'), 140.00, 'Yape');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (412, 'BMS-0012', 212, TO_DATE('2025-05-14','YYYY-MM-DD'), 40.50, 'Efectivo');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (413, 'BMS-0013', 213, TO_DATE('2025-05-15','YYYY-MM-DD'), 107.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (414, 'BMS-0014', 214, TO_DATE('2025-05-15','YYYY-MM-DD'), 60.50, 'Efectivo');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (415, 'BMS-0015', 215, TO_DATE('2025-05-15','YYYY-MM-DD'), 76.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (416, 'BMS-0016', 216, TO_DATE('2025-05-15','YYYY-MM-DD'), 40.50, 'Efectivo');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (417, 'BMS-0017', 217, TO_DATE('2025-05-16','YYYY-MM-DD'), 123.50, 'Tarjeta');
INSERT INTO BOLETAS (BOLETA_ID, NRO_SERIE, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, METODO_PAGO) VALUES (418, 'BMS-0018', 218, TO_DATE('2025-05-16','YYYY-MM-DD'), 80.50, 'Yape');

-- BOLETAS_SERVICIOS
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (401, 301, 50.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (402, 302, 60.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (403, 303, 70.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (404, 304, 80.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (405, 305, 90.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (406, 306, 40.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (407, 307, 50.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (408, 308, 60.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (409, 309, 70.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (410, 310, 80.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (411, 311, 90.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (412, 312, 40.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (413, 313, 50.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (414, 314, 60.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (415, 307, 50.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (416, 306, 40.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (417, 305, 90.50, 1);
INSERT INTO BOLETAS_SERVICIOS (BOLETA_ID, SERVICIO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (418, 304, 80.50, 1);

-- BOLETAS_MEDICAMENTOS
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (401, 701, 9.50, 2);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (403, 703, 13.00, 3);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (405, 705, 16.50, 1);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (407, 707, 9.50, 4);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (409, 709, 13.00, 5);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (411, 711, 16.50, 3);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (413, 713, 9.50, 6);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (415, 715, 13.00, 2);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, PRECIO_UNITARIO, CANTIDAD) VALUES (417, 717, 16.50, 2);


DELETE FROM BOLETAS_MEDICAMENTOS WHERE BOLETA_ID BETWEEN 3050 AND 3062;
DELETE FROM BOLETAS WHERE BOLETA_ID BETWEEN 3050 AND 3062;

DELETE FROM RECETAS_MEDICAMENTOS WHERE RECETA_ID BETWEEN 730 AND 753;
DELETE FROM RECETAS_MEDICAS      WHERE RECETA_ID BETWEEN 730 AND 753;

INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (730, 511, DATE '2025-05-12');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (731, 512, DATE '2025-05-13');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (732, 513, DATE '2025-05-14');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (733, 514, DATE '2025-05-15');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (734, 515, DATE '2025-05-16');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (735, 516, DATE '2025-06-01');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (736, 517, DATE '2025-06-02');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (737, 518, DATE '2025-06-03');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (738, 519, DATE '2025-06-04');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (739, 520, DATE '2025-06-05');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (740, 511, DATE '2025-07-10');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (741, 512, DATE '2025-07-12');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (742, 513, DATE '2025-07-15');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (743, 514, DATE '2025-08-01');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (744, 515, DATE '2025-08-08');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (745, 516, DATE '2025-09-10');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (746, 517, DATE '2025-09-15');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (747, 518, DATE '2025-09-20');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (748, 519, DATE '2025-10-01');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (749, 520, DATE '2025-10-02');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (750, 511, DATE '2025-10-03');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (751, 512, DATE '2025-10-04');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (752, 513, DATE '2025-10-05');
INSERT INTO RECETAS_MEDICAS (RECETA_ID, ATENCION_ID, FECHA_EMISION) VALUES (753, 514, DATE '2025-10-06');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (730, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (730, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (731, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (731, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (732, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (732, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (733, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (733, 718, 1, 2.0, 5, 'Oral');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (734, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (734, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (735, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (735, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (736, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (736, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (737, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (737, 718, 1, 2.0, 5, 'Oral');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (738, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (738, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (739, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (739, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (740, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (740, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (741, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (741, 718, 1, 2.0, 5, 'Oral');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (742, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (742, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (743, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (743, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (744, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (744, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (745, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (745, 718, 1, 2.0, 5, 'Oral');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (746, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (746, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (747, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (747, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (748, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (748, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (749, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (749, 718, 1, 2.0, 5, 'Oral');

INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (750, 702, 1, 3.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (750, 703, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (751, 704, 1, 3.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (751, 708, 1, 1.0, 30, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (752, 712, 1, 2.0, 5, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (752, 713, 1, 1.0, 3, 'Oral');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (753, 715, 1, 2.0, 10, 'Tópica');
INSERT INTO RECETAS_MEDICAMENTOS (RECETA_ID, MEDICAMENTO_ID, CANTIDAD_DOSIS, FRECUENCIA, DURACION, VIA_ADMINISTRACION) VALUES (753, 718, 1, 2.0, 5, 'Oral');


INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3050, 201, DATE '2025-05-12', 25.00, 'B3050', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3051, 202, DATE '2025-05-13', 40.00, 'B3051', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3052, 203, DATE '2025-06-02', 30.00, 'B3052', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3053, 204, DATE '2025-06-04', 20.00, 'B3053', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3054, 205, DATE '2025-07-11', 60.00, 'B3054', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3055, 206, DATE '2025-07-15', 15.00, 'B3055', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3056, 207, DATE '2025-08-02', 12.00, 'B3056', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3057, 208, DATE '2025-08-08', 28.00, 'B3057', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3058, 209, DATE '2025-09-11', 10.00, 'B3058', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3059, 210, DATE '2025-09-20', 18.00, 'B3059', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3060, 211, DATE '2025-10-01', 22.00, 'B3060', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3061, 212, DATE '2025-10-08', 35.00, 'B3061', 'EFECTIVO');
INSERT INTO BOLETAS (BOLETA_ID, PACIENTE_ID, FECHA_EMISION, MONTO_TOTAL, NRO_SERIE, METODO_PAGO) VALUES (3062, 213, DATE '2025-10-08', 19.00, 'B3062', 'EFECTIVO');


INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3050, 702, 1, 10.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3050, 703, 1, 12.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3051, 704, 1, 15.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3052, 703, 1, 12.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3053, 715, 1, 14.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3054, 712, 1, 11.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3055, 702, 1, 10.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3056, 718, 1, 13.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3057, 708, 1, 16.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3058, 703, 1, 12.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3059, 702, 1, 10.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3060, 713, 1, 17.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3061, 712, 1, 11.00);
INSERT INTO BOLETAS_MEDICAMENTOS (BOLETA_ID, MEDICAMENTO_ID, CANTIDAD, PRECIO_UNITARIO) VALUES (3062, 704, 1, 15.00);

COMMIT;
