CREATE TABLE L5_AREAS_TEMATICAS (
    AREA_TEMATICA_ID NUMBER NOT NULL,
    NOMBRE           VARCHAR2(50),
    DESCRIPCION      VARCHAR2(200)
)
LOGGING;

ALTER TABLE L5_AREAS_TEMATICAS ADD CONSTRAINT L5_AREAS_TEMATICAS_PK PRIMARY KEY ( AREA_TEMATICA_ID );

CREATE TABLE L5_BIBLIOGRAFIA_CURSOS (
    CURSO_ID          NUMBER NOT NULL,
    LIBRO_ID          NUMBER NOT NULL,
    TIPO_BIBLIOGRAFIA VARCHAR2(20)
)
LOGGING;

ALTER TABLE L5_BIBLIOGRAFIA_CURSOS
    ADD CONSTRAINT L5_BIBLIOGRAFIA_CURSOS_TIPO_CK CHECK ( TIPO_BIBLIOGRAFIA IN ( 'OBLIGATORIA', 'COMPLEMENTARIA' ) );

ALTER TABLE L5_BIBLIOGRAFIA_CURSOS ADD CONSTRAINT L5_BIBLIOGRAFIA_CURSOS_PK PRIMARY KEY ( CURSO_ID,
                                                                                       LIBRO_ID );

CREATE TABLE L5_CAMPANIAS (
    CAMPANIA_ID          NUMBER NOT NULL,
    NOMBRE               VARCHAR2(100),
    DESCRIPCION          VARCHAR2(200),
    FECHA_INICIO         DATE,
    FECHA_FIN            DATE,
    PORCENTAJE_DESCUENTO NUMBER(5, 2)
)
LOGGING;

ALTER TABLE L5_CAMPANIAS ADD CONSTRAINT L5_CAMPANIAS_PK PRIMARY KEY ( CAMPANIA_ID );

CREATE TABLE L5_CAMPANIAS_PRODUCTOS (
    CAMPANIA_ID          NUMBER NOT NULL,
    PRODUCTO_ID          NUMBER NOT NULL,
    PORCENTAJE_DESCUENTO NUMBER(5, 2)
)
LOGGING;

ALTER TABLE L5_CAMPANIAS_PRODUCTOS ADD CONSTRAINT L5_CAMPANIAS_PRODUCTOS_PK PRIMARY KEY ( CAMPANIA_ID,
                                                                                       PRODUCTO_ID );

CREATE TABLE L5_CATEGORIAS (
    CATEGORIA_ID NUMBER NOT NULL,
    NOMBRE       VARCHAR2(50),
    DESCRIPCION  VARCHAR2(200)
)
LOGGING;

ALTER TABLE L5_CATEGORIAS ADD CONSTRAINT L5_CATEGORIAS_PK PRIMARY KEY ( CATEGORIA_ID );

CREATE TABLE L5_CLIENTES (
    CLIENTE_ID      NUMBER NOT NULL,
    TIPO_CLIENTE_ID NUMBER,
    NOMBRE          VARCHAR2(100),
    APELLIDO        VARCHAR2(100),
    EMAIL           VARCHAR2(100),
    TELEFONO        VARCHAR2(20),
    CODIGO_PUCP     VARCHAR2(20)
)
LOGGING;

ALTER TABLE L5_CLIENTES ADD CONSTRAINT L5_CLIENTES_PK PRIMARY KEY ( CLIENTE_ID );

CREATE TABLE L5_CURSOS (
    CURSO_ID NUMBER NOT NULL,
    CODIGO   VARCHAR2(20),
    NOMBRE   VARCHAR2(200),
    FACULTAD VARCHAR2(100)
)
LOGGING;

ALTER TABLE L5_CURSOS ADD CONSTRAINT L5_CURSOS_PK PRIMARY KEY ( CURSO_ID );

CREATE TABLE L5_EDITORIALES (
    EDITORIAL_ID          NUMBER NOT NULL,
    NOMBRE                VARCHAR2(100),
    PAIS_ORIGEN           VARCHAR2(50),
    ESPECIALIDAD_TEMATICA VARCHAR2(100),
    CONTACTO_NOMBRE       VARCHAR2(100),
    CONTACTO_EMAIL        VARCHAR2(100),
    CONTACTO_TELEFONO     VARCHAR2(20)
)
LOGGING;

ALTER TABLE L5_EDITORIALES ADD CONSTRAINT L5_EDITORIALES_PK PRIMARY KEY ( EDITORIAL_ID );

CREATE TABLE L5_EDITORIALES_HISTORICO (
    HISTORICO_ID            NUMBER NOT NULL,
    EDITORIAL_ID            NUMBER,
    FECHA_REGISTRO          DATE,
    TIEMPO_ENTREGA_PROMEDIO NUMBER,
    PORCENTAJE_CUMPLIMIENTO NUMBER(5, 2),
    CALIFICACION_SERVICIO   NUMBER(2, 1),
    PERIODO_EVALUACION      VARCHAR2(20)
)
LOGGING;

ALTER TABLE L5_EDITORIALES_HISTORICO ADD CONSTRAINT L5_EDITORIALES_HISTORICO_PK PRIMARY KEY ( HISTORICO_ID );

CREATE TABLE L5_ENCUESTAS (
    ENCUESTA_ID            NUMBER NOT NULL,
    CLIENTE_ID             NUMBER,
    VENTA_ID               NUMBER,
    FECHA_ENCUESTA         DATE,
    CALIFICACION_SERVICIO  NUMBER(2, 1),
    CALIFICACION_PRODUCTOS NUMBER(2, 1),
    COMENTARIOS            VARCHAR2(500)
)
LOGGING;

ALTER TABLE L5_ENCUESTAS ADD CONSTRAINT L5_ENCUESTAS_PK PRIMARY KEY ( ENCUESTA_ID );

CREATE TABLE L5_INCIDENCIAS (
    INCIDENCIA_ID    NUMBER NOT NULL,
    CLIENTE_ID       NUMBER,
    VENTA_ID         NUMBER,
    PRODUCTO_ID      NUMBER,
    FECHA_INCIDENCIA DATE,
    TIPO_INCIDENCIA  VARCHAR2(50),
    DESCRIPCION      VARCHAR2(500),
    ESTADO           VARCHAR2(20),
    SOLUCION         VARCHAR2(500)
)
LOGGING;

ALTER TABLE L5_INCIDENCIAS
    ADD CONSTRAINT L5_INCIDENCIAS_ESTADO_CK CHECK ( ESTADO IN ( 'REGISTRADA', 'EN_PROCESO', 'RESUELTA', 'CERRADA' ) );

ALTER TABLE L5_INCIDENCIAS ADD CONSTRAINT L5_INCIDENCIAS_PK PRIMARY KEY ( INCIDENCIA_ID );

CREATE TABLE L5_LIBROS (
    LIBRO_ID            NUMBER NOT NULL,
    PRODUCTO_ID         NUMBER,
    ISBN                VARCHAR2(13),
    ANIO_PUBLICACION    NUMBER(4),
    EDICION             VARCHAR2(50),
    IDIOMA              VARCHAR2(30),
    NUM_PAGINAS         NUMBER,
    DIMENSIONES         VARCHAR2(50),
    PESO                NUMBER(6, 2),
    TIPO_ENCUADERNACION VARCHAR2(50)
)
LOGGING;

ALTER TABLE L5_LIBROS ADD CONSTRAINT L5_LIBROS_PK PRIMARY KEY ( LIBRO_ID );

CREATE TABLE L5_ORDENES_COMPRA (
    ORDEN_COMPRA_ID        NUMBER NOT NULL,
    EDITORIAL_ID           NUMBER,
    FECHA_ORDEN            DATE,
    FECHA_ENTREGA_OBJETIVO DATE,
    TIPO_ORDEN             VARCHAR2(20),
    ESTADO                 VARCHAR2(20),
    PRESUPUESTO_ASIGNADO   NUMBER(12, 2),
    COSTO_LOGISTICO        NUMBER(10, 2),
    JUSTIFICACION          VARCHAR2(400)
)
LOGGING;

ALTER TABLE L5_ORDENES_COMPRA
    ADD CONSTRAINT L5_ORDENES_COMPRA_ESTADO_CK CHECK ( ESTADO IN ( 'PENDIENTE', 'APROBADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA' ) );

ALTER TABLE L5_ORDENES_COMPRA
    ADD CONSTRAINT L5_ORDENES_COMPRA_TIPO_CK CHECK ( TIPO_ORDEN IN ( 'PROGRAMADA', 'EXTRAORDINARIA' ) );

ALTER TABLE L5_ORDENES_COMPRA ADD CONSTRAINT L5_ORDENES_COMPRA_PK PRIMARY KEY ( ORDEN_COMPRA_ID );

CREATE TABLE L5_ORDENES_COMPRA_DETALLE (
    ORDEN_COMPRA_ID NUMBER NOT NULL,
    PRODUCTO_ID     NUMBER NOT NULL,
    CANTIDAD        NUMBER,
    PRECIO_UNITARIO NUMBER(10, 2)
)
LOGGING;

ALTER TABLE L5_ORDENES_COMPRA_DETALLE ADD CONSTRAINT L5_ORDENES_COMPRA_DETALLE_PK PRIMARY KEY ( ORDEN_COMPRA_ID,
                                                                                      PRODUCTO_ID );

CREATE TABLE L5_PEDIDOS_ESPECIALES (
    PEDIDO_ESPECIAL_ID     NUMBER NOT NULL,
    CLIENTE_ID             NUMBER,
    FECHA_SOLICITUD        DATE,
    FECHA_ENTREGA_ESTIMADA DATE,
    ESTADO                 VARCHAR2(20),
    MONTO_ADELANTO         NUMBER(10, 2),
    OBSERVACIONES          VARCHAR2(400)
)
LOGGING;

ALTER TABLE L5_PEDIDOS_ESPECIALES
    ADD CONSTRAINT L5_PED_ESP_ESTADO_CK CHECK ( ESTADO IN ( 'SOLICITADO', 'EN_PROCESO', 'LISTO', 'ENTREGADO', 'CANCELADO' ) );

ALTER TABLE L5_PEDIDOS_ESPECIALES ADD CONSTRAINT L5_PEDIDOS_ESPECIALES_PK PRIMARY KEY ( PEDIDO_ESPECIAL_ID );

CREATE TABLE L5_PEDIDOS_ESPECIALES_DETALLE (
    PEDIDO_ESPECIAL_ID NUMBER NOT NULL,
    PRODUCTO_ID        NUMBER NOT NULL,
    CANTIDAD           NUMBER,
    PRECIO_UNITARIO    NUMBER(10, 2)
)
LOGGING;

ALTER TABLE L5_PEDIDOS_ESPECIALES_DETALLE ADD CONSTRAINT L5_PED_ESP_DETALLE_PK PRIMARY KEY ( PEDIDO_ESPECIAL_ID,
                                                                                             PRODUCTO_ID );

CREATE TABLE L5_PERDIDAS_INVENTARIO (
    PERDIDA_ID     NUMBER NOT NULL,
    PRODUCTO_ID    NUMBER,
    FECHA_REGISTRO DATE,
    CANTIDAD       NUMBER,
    TIPO_PERDIDA   VARCHAR2(20),
    MOTIVO         VARCHAR2(200)
)
LOGGING;

ALTER TABLE L5_PERDIDAS_INVENTARIO
    ADD CONSTRAINT L5_PERDIDAS_INVENTARIO_TIPO_CK CHECK ( TIPO_PERDIDA IN ( 'DETERIORO', 'PERDIDA', 'AJUSTE' ) );

ALTER TABLE L5_PERDIDAS_INVENTARIO ADD CONSTRAINT L5_PERDIDAS_INVENTARIO_PK PRIMARY KEY ( PERDIDA_ID );

CREATE TABLE L5_PRECIOS_TIPO_CLIENTE (
    PRODUCTO_ID          NUMBER NOT NULL,
    TIPO_CLIENTE_ID      NUMBER NOT NULL,
    PORCENTAJE_DESCUENTO NUMBER(5, 2)
)
LOGGING;

ALTER TABLE L5_PRECIOS_TIPO_CLIENTE ADD CONSTRAINT L5_PRECIOS_TIPO_CLIENTE_PK PRIMARY KEY ( PRODUCTO_ID,
                                                                                 TIPO_CLIENTE_ID );

CREATE TABLE L5_PRODUCTOS (
    PRODUCTO_ID       NUMBER NOT NULL,
    CODIGO_PRODUCTO   VARCHAR2(20),
    NOMBRE            VARCHAR2(100),
    DESCRIPCION       VARCHAR2(400),
    CATEGORIA_ID      NUMBER,
    PRECIO_BASE       NUMBER(10, 2),
    STOCK_ACTUAL      NUMBER,
    STOCK_MINIMO      NUMBER,
    STOCK_SEGURIDAD   NUMBER,
    ESTADO            VARCHAR2(20),
    EDITORIAL_ID      NUMBER,
    UBICACION_ALMACEN VARCHAR2(50)
)
LOGGING;

ALTER TABLE L5_PRODUCTOS
    ADD CONSTRAINT L5_PRODUCTOS_ESTADO_CK CHECK ( ESTADO IN ( 'ACTIVO', 'DESCONTINUADO', 'AGOTADO' ) );

ALTER TABLE L5_PRODUCTOS ADD CONSTRAINT L5_PRODUCTOS_PK PRIMARY KEY ( PRODUCTO_ID );

CREATE TABLE L5_PRODUCTOS_AREAS (
    PRODUCTO_ID      NUMBER NOT NULL,
    AREA_TEMATICA_ID NUMBER NOT NULL
)
LOGGING;

ALTER TABLE L5_PRODUCTOS_AREAS ADD CONSTRAINT L5_PRODUCTOS_AREAS_PK PRIMARY KEY ( PRODUCTO_ID,
                                                                               AREA_TEMATICA_ID );

CREATE TABLE L5_PRODUCTOS_CONDICION (
    CONDICION_ID      NUMBER NOT NULL,
    PRODUCTO_ID       NUMBER,
    FECHA_REVISION    DATE,
    CONDICION_FISICA  VARCHAR2(50),
    UBICACION_ALMACEN VARCHAR2(100),
    OBSERVACIONES     VARCHAR2(400)
)
LOGGING;

ALTER TABLE L5_PRODUCTOS_CONDICION ADD CONSTRAINT L5_PRODUCTOS_CONDICION_PK PRIMARY KEY ( CONDICION_ID );

CREATE TABLE L5_REVISTAS (
    REVISTA_ID  NUMBER NOT NULL,
    PRODUCTO_ID NUMBER,
    ISSN        VARCHAR2(8),
    VOLUMEN     VARCHAR2(20),
    NUMERO      VARCHAR2(20),
    PERIODO     VARCHAR2(50)
)
LOGGING;

ALTER TABLE L5_REVISTAS ADD CONSTRAINT L5_REVISTAS_PK PRIMARY KEY ( REVISTA_ID );

CREATE TABLE L5_SUGERENCIAS (
    SUGERENCIA_ID    NUMBER NOT NULL,
    CLIENTE_ID       NUMBER,
    FECHA_SUGERENCIA DATE,
    TIPO_SUGERENCIA  VARCHAR2(50),
    DESCRIPCION      VARCHAR2(500),
    ESTADO           VARCHAR2(20)
)
LOGGING;

ALTER TABLE L5_SUGERENCIAS
    ADD CONSTRAINT L5_SUGERENCIAS_ESTADO_CK CHECK ( ESTADO IN ( 'REGISTRADA', 'EN_REVISION', 'IMPLEMENTADA', 'RECHAZADA' ) );

ALTER TABLE L5_SUGERENCIAS ADD CONSTRAINT L5_SUGERENCIAS_PK PRIMARY KEY ( SUGERENCIA_ID );

CREATE TABLE L5_TIPOS_CLIENTE (
    TIPO_CLIENTE_ID NUMBER NOT NULL,
    NOMBRE          VARCHAR2(50),
    DESCRIPCION     VARCHAR2(200)
)
LOGGING;

ALTER TABLE L5_TIPOS_CLIENTE ADD CONSTRAINT L5_TIPOS_CLIENTE_PK PRIMARY KEY ( TIPO_CLIENTE_ID );

CREATE TABLE L5_VENTAS (
    VENTA_ID            NUMBER NOT NULL,
    CLIENTE_ID          NUMBER,
    FECHA_VENTA         DATE,
    TOTAL_BRUTO         NUMBER(12, 2),
    TOTAL_DESCUENTOS    NUMBER(12, 2),
    TOTAL_NETO          NUMBER(12, 2),
    METODO_PAGO         VARCHAR2(50),
    CODIGO_AUTORIZACION VARCHAR2(50),
    CENTRO_COSTO        VARCHAR2(50)
)
LOGGING;

ALTER TABLE L5_VENTAS ADD CONSTRAINT L5_VENTAS_PK PRIMARY KEY ( VENTA_ID );

CREATE TABLE L5_VENTAS_DETALLE (
    VENTA_ID               NUMBER NOT NULL,
    PRODUCTO_ID            NUMBER NOT NULL,
    CANTIDAD               NUMBER,
    PRECIO_UNITARIO        NUMBER(10, 2),
    DESCUENTO_TIPO_CLIENTE NUMBER(10, 2),
    DESCUENTO_CAMPANIA     NUMBER(10, 2),
    PRECIO_FINAL           NUMBER(10, 2),
    CAMPANIA_ID            NUMBER
)
LOGGING;

ALTER TABLE L5_VENTAS_DETALLE ADD CONSTRAINT L5_VENTAS_DETALLE_PK PRIMARY KEY ( VENTA_ID,
                                                                             PRODUCTO_ID );

ALTER TABLE L5_BIBLIOGRAFIA_CURSOS
    ADD CONSTRAINT L5_BIB_CUR_CUR_FK FOREIGN KEY ( CURSO_ID )
        REFERENCES L5_CURSOS ( CURSO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_BIBLIOGRAFIA_CURSOS
    ADD CONSTRAINT L5_BIB_CUR_LIB_FK FOREIGN KEY ( LIBRO_ID )
        REFERENCES L5_LIBROS ( LIBRO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_CAMPANIAS_PRODUCTOS
    ADD CONSTRAINT L5_CAM_PRO_CAM_FK FOREIGN KEY ( CAMPANIA_ID )
        REFERENCES L5_CAMPANIAS ( CAMPANIA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_CAMPANIAS_PRODUCTOS
    ADD CONSTRAINT L5_CAM_PRO_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_CLIENTES
    ADD CONSTRAINT L5_CLIENTES_TIPOS_CLIENTE_FK FOREIGN KEY ( TIPO_CLIENTE_ID )
        REFERENCES L5_TIPOS_CLIENTE ( TIPO_CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRODUCTOS_CONDICION
    ADD CONSTRAINT L5_PRO_CON_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_ENCUESTAS
    ADD CONSTRAINT L5_ENCUESTAS_CLIENTES_FK FOREIGN KEY ( CLIENTE_ID )
        REFERENCES L5_CLIENTES ( CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_ENCUESTAS
    ADD CONSTRAINT L5_ENCUESTAS_VENTAS_FK FOREIGN KEY ( VENTA_ID )
        REFERENCES L5_VENTAS ( VENTA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_EDITORIALES_HISTORICO
    ADD CONSTRAINT L5_EDI_HIS_EDI_FK FOREIGN KEY ( EDITORIAL_ID )
        REFERENCES L5_EDITORIALES ( EDITORIAL_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_INCIDENCIAS
    ADD CONSTRAINT L5_INCIDENCIAS_CLIENTES_FK FOREIGN KEY ( CLIENTE_ID )
        REFERENCES L5_CLIENTES ( CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_INCIDENCIAS
    ADD CONSTRAINT L5_INCIDENCIAS_PRODUCTOS_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_INCIDENCIAS
    ADD CONSTRAINT L5_INCIDENCIAS_VENTAS_FK FOREIGN KEY ( VENTA_ID )
        REFERENCES L5_VENTAS ( VENTA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_LIBROS
    ADD CONSTRAINT L5_LIBROS_PRODUCTOS_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_ORDENES_COMPRA_DETALLE
    ADD CONSTRAINT L5_ORD_COM_DET_ORD_FK FOREIGN KEY ( ORDEN_COMPRA_ID )
        REFERENCES L5_ORDENES_COMPRA ( ORDEN_COMPRA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_ORDENES_COMPRA_DETALLE
    ADD CONSTRAINT L5_ORD_COM_DET_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_ORDENES_COMPRA
    ADD CONSTRAINT L5_ORD_COM_EDI_FK FOREIGN KEY ( EDITORIAL_ID )
        REFERENCES L5_EDITORIALES ( EDITORIAL_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PEDIDOS_ESPECIALES_DETALLE
    ADD CONSTRAINT L5_PED_ESP_DET_PED_FK FOREIGN KEY ( PEDIDO_ESPECIAL_ID )
        REFERENCES L5_PEDIDOS_ESPECIALES ( PEDIDO_ESPECIAL_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PEDIDOS_ESPECIALES_DETALLE
    ADD CONSTRAINT L5_PED_ESP_DET_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PEDIDOS_ESPECIALES
    ADD CONSTRAINT L5_PED_ESP_CLI_FK FOREIGN KEY ( CLIENTE_ID )
        REFERENCES L5_CLIENTES ( CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PERDIDAS_INVENTARIO
    ADD CONSTRAINT L5_PER_INV_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRECIOS_TIPO_CLIENTE
    ADD CONSTRAINT L5_PRE_TIP_CLI_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRECIOS_TIPO_CLIENTE
    ADD CONSTRAINT L5_PRE_TIP_CLI_TIP_FK FOREIGN KEY ( TIPO_CLIENTE_ID )
        REFERENCES L5_TIPOS_CLIENTE ( TIPO_CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRODUCTOS_AREAS
    ADD CONSTRAINT L5_PRODUCTOS_AREAS_AREAS_FK FOREIGN KEY ( AREA_TEMATICA_ID )
        REFERENCES L5_AREAS_TEMATICAS ( AREA_TEMATICA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRODUCTOS_AREAS
    ADD CONSTRAINT L5_PRO_ARE_PRO_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRODUCTOS
    ADD CONSTRAINT L5_PRODUCTOS_CATEGORIAS_FK FOREIGN KEY ( CATEGORIA_ID )
        REFERENCES L5_CATEGORIAS ( CATEGORIA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_PRODUCTOS
    ADD CONSTRAINT L5_PRODUCTOS_EDITORIALES_FK FOREIGN KEY ( EDITORIAL_ID )
        REFERENCES L5_EDITORIALES ( EDITORIAL_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_REVISTAS
    ADD CONSTRAINT L5_REVISTAS_PRODUCTOS_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_SUGERENCIAS
    ADD CONSTRAINT L5_SUGERENCIAS_CLIENTES_FK FOREIGN KEY ( CLIENTE_ID )
        REFERENCES L5_CLIENTES ( CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_VENTAS
    ADD CONSTRAINT L5_VENTAS_CLIENTES_FK FOREIGN KEY ( CLIENTE_ID )
        REFERENCES L5_CLIENTES ( CLIENTE_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_VENTAS_DETALLE
    ADD CONSTRAINT L5_VENTAS_DETALLE_CAMPANIAS_FK FOREIGN KEY ( CAMPANIA_ID )
        REFERENCES L5_CAMPANIAS ( CAMPANIA_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_VENTAS_DETALLE
    ADD CONSTRAINT L5_VENTAS_DETALLE_PRODUCTOS_FK FOREIGN KEY ( PRODUCTO_ID )
        REFERENCES L5_PRODUCTOS ( PRODUCTO_ID )
    NOT DEFERRABLE;

ALTER TABLE L5_VENTAS_DETALLE
    ADD CONSTRAINT L5_VENTAS_DETALLE_VENTAS_FK FOREIGN KEY ( VENTA_ID )
        REFERENCES L5_VENTAS ( VENTA_ID )
    NOT DEFERRABLE;