DROP TABLE bs_categoria CASCADE CONSTRAINTS;

DROP TABLE bs_cliente CASCADE CONSTRAINTS;

DROP TABLE bs_detalle_guia CASCADE CONSTRAINTS;

DROP TABLE bs_detalle_orden CASCADE CONSTRAINTS;

DROP TABLE bs_detalle_venta CASCADE CONSTRAINTS;

DROP TABLE bs_empleado CASCADE CONSTRAINTS;

DROP TABLE bs_guiapreventa CASCADE CONSTRAINTS;

DROP TABLE bs_guiasastreria CASCADE CONSTRAINTS;

DROP TABLE bs_inventario CASCADE CONSTRAINTS;

DROP TABLE bs_matriz_talla CASCADE CONSTRAINTS;

DROP TABLE bs_orden_fabricacion CASCADE CONSTRAINTS;

DROP TABLE bs_persona CASCADE CONSTRAINTS;

DROP TABLE bs_prenda CASCADE CONSTRAINTS;

DROP TABLE bs_tienda CASCADE CONSTRAINTS;

DROP TABLE bs_venta CASCADE CONSTRAINTS;
