--Nuevo intento 2026.0


--Pregunta1
CREATE TABLE CITAS_MEDICAS(
    CITA_ID NUMBER PRIMARY KEY,
    PACIENTE_ID NUMBER NOT NULL,
    PERSONAL_ID NUMBER NOT NULL,
    FECHA_CITA DATE NOT NULL,
    HORA_CITA DATE NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'Programada'
);

--Pregunta2

CREATE TABLE RESULTADOS_LABORATORIO(
    RESULTADO_ID NUMBER PRIMARY KEY,
    ATENCION_ID NUMBER NOT NULL,
    TIPO_PRUEBA VARCHAR2(100) NOT NULL,
    FECHA_RESULTADO DATE NOT NULL,
    VALOR_RESULTADO VARCHAR2(100) NOT NULL
);

--Pregunta3

COMMENT ON COLUMN BOLETAS.BOLETA_ID IS 'Identificador único de la boleta de pago';
COMMENT ON COLUMN BOLETAS.PACIENTE_ID IS 'Paciente asociado a la boleta';
COMMENT ON COLUMN BOLETAS.FECHA_EMISION IS 'Fecha en que se emitió la boleta';
COMMENT ON COLUMN BOLETAS.MONTO_TOTAL IS 'Monto total facturado';
COMMENT ON COLUMN BOLETAS.METODO_PAGO IS 'Método de pago utilizado (efectivo, tarjeta, etc';
COMMENT ON COLUMN BOLETAS.NRO_SERIE IS 'Número de serie de la boleta';

--Pregunta4
CREATE TABLE INVENTARIO_MEDICAMENTOS (
    INVENTARIO_ID NUMBER PRIMARY KEY,
    MEDICAMENTO_ID NUMBER NOT NULL,
    UBICACION VARCHAR2(100) NOT NULL,
    CANTIDAD NUMBER 
);

--SELECT * FROM MEDICAMENTOS;
--Pregunta5
ALTER TABLE INVENTARIO_MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTO_ID FOREIGN KEY (MEDICAMENTO_ID)
REFERENCES  MEDICAMENTOS(MEDICAMENTO_ID);

--PREGUNTA 6
SELECT * FROM PACIENTES;
ALTER TABLE PACIENTES RENAME COLUMN APELLIDOS TO PRIMER_APELLIDO;
ALTER TABLE PACIENTES MODIFY PRIMER_APELLIDO VARCHAR2(50 BYTE);
ALTER TABLE PACIENTES ADD (SEGUNDO_APELLIDO VARCHAR2(50 BYTE));

--Pregunta 7
--PACIENTE CON CITAS MEDICAS
ALTER TABLE CITAS_MEDICAS ADD CONSTRAINT FK_PACIENTE_ID FOREIGN KEY (PACIENTE_ID)
REFERENCES PACIENTES(PACIENTE_ID);
--PERSONAL CON CITAS
ALTER TABLE CITAS_MEDICAS ADD CONSTRAINT FK_PERSONAL_ID FOREIGN KEY(PERSONAL_ID)
REFERENCES PERSONALES_MEDICOS(PERSONAL_ID);

--PREGUNTA 8
--FK A RESULTADOS_LABORATORIO
ALTER TABLE RESULTADOS_LABORATORIO ADD CONSTRAINT FK_ATENCION_RESULTADO FOREIGN KEY (ATENCION_ID)
REFERENCES ATENCIONES_MEDICAS(ATENCION_ID);

--Pregunta9 
ALTER TABLE PACIENTES ADD CONSTRAINT CH_SEXO CHECK (SEXO='M' OR SEXO ='F');

--Pregunta10
ALTER TABLE RECETAS_MEDICAMENTOS ADD CONSTRAINT CH_CANTIDAD CHECK (CANTIDAD_DOSIS>0);

ALTER TABLE BOLETAS ADD CONSTRAINT CH_MONTO CHECK(MONTO_TOTAL>0);

--Pregunta 11
ALTER TABLE PACIENTES MODIFY NRO_DOCUMENTO VARCHAR2(15);
ALTER TABLE PACIENTES MODIFY NOMBRE VARCHAR2(80);

--Pregunta 12
ALTER TABLE MEDICAMENTOS ADD (LOTE VARCHAR2(50), FECHA_VENCIMIENTO DATE, PRESENTACION VARCHAR2(50));
COMMENT ON COLUMN MEDICAMENTOS.LOTE IS 'Identificador del lote de fabricacion';
COMMENT ON COLUMN MEDICAMENTOS.FECHA_VENCIMIENTO IS 'Fecha límite de uso del medicamento';
COMMENT ON COLUMN MEDICAMENTOS.PRESENTACION IS 'Formato físico del medicamento';

--Pregunta 13
ALTER TABLE PACIENTES ADD (USUARIO_CREACION NUMBER, FECHA_CREACION DATE, USUARIO_ULT_MODIF NUMBER, FECHA_ULT_MODIF DATE);
COMMENT ON COLUMN PACIENTES.USUARIO_CREACION IS 'Identificador del usuario que creó el registro';
COMMENT ON COLUMN PACIENTES.FECHA_CREACION IS 'Identificador del usuario que modificó por última vez el registro';
COMMENT ON COLUMN PACIENTES.FECHA_ULT_MODIF IS 'Fecha de la última modificación del registro';