
DROP TABLE L1_PROGRAMACION ;

DROP TABLE L1_PROGRAMA ;

DROP TABLE L1_TIPOPUBLICO ;

DROP TABLE L1_TIPOPROGRAMA;

DROP TABLE L1_RATING ;

DROP TABLE L1_CANALXPAQUETE ;

DROP TABLE L1_PAQUETE ;

DROP TABLE L1_CANAL ;

DROP TABLE L1_PAIS ;

DROP TABLE L1_TIPOCANAL ;

DROP TABLE L1_CATEGORIA ;


CREATE TABLE L1_CANAL
(
    id_canal             INTEGER NOT NULL ,
    nombre               VARCHAR(100) NOT NULL ,
    numero               INTEGER NOT NULL ,
    id_categoria         INTEGER NOT NULL ,
    id_tipocanal         INTEGER NOT NULL ,
    id_pais              INTEGER NOT NULL 
);

ALTER TABLE L1_CANAL ADD CONSTRAINT XPKCANAL PRIMARY KEY (id_canal);

CREATE TABLE L1_CANALXPAQUETE
(
    id_canal             INTEGER NOT NULL ,
    id_paquete           INTEGER NOT NULL ,
    fechaingreso         DATE NOT NULL ,
    fechasalida          DATE NULL 
);

ALTER TABLE L1_CANALXPAQUETE ADD CONSTRAINT XPKCANALXPAQUETE PRIMARY KEY (id_canal,id_paquete);

CREATE TABLE L1_CATEGORIA
(
    id_categoria         INTEGER NOT NULL ,
    nombre               VARCHAR(100) NOT NULL 
);

ALTER TABLE L1_CATEGORIA ADD CONSTRAINT XPKCATEGORIA PRIMARY KEY (id_categoria);

CREATE TABLE L1_PAIS
(
    id_pais              INTEGER NOT NULL ,
    nombre               VARCHAR(100) NOT NULL 
);

ALTER TABLE L1_PAIS ADD CONSTRAINT XPKPAIS PRIMARY KEY (id_pais);

CREATE TABLE L1_PAQUETE
(
    id_paquete           INTEGER NOT NULL ,
    nombre               VARCHAR(100) NOT NULL ,
    tarifa               FLOAT NOT NULL ,
    vigente              INTEGER NOT NULL 
);

ALTER TABLE L1_PAQUETE ADD CONSTRAINT XPKPAQUETE PRIMARY KEY (id_paquete);

CREATE TABLE L1_PROGRAMA
(
    id_programa          INTEGER NOT NULL ,
    titulo               VARCHAR(100) NOT NULL ,
    comentarios          VARCHAR(100) NOT NULL ,
    duracion             INTEGER NOT NULL ,
    id_tipoprograma      INTEGER NOT NULL ,
    id_tipopublico       INTEGER NOT NULL ,
    id_categoria         INTEGER NOT NULL 
);

ALTER TABLE L1_PROGRAMA ADD CONSTRAINT XPKPROGRAMA PRIMARY KEY (id_programa);

CREATE TABLE L1_PROGRAMACION
(
    id_programa          INTEGER NOT NULL ,
    id_canal             INTEGER NOT NULL ,
    fechahorainicio      DATE NOT NULL ,
    fechahorafin         DATE NOT NULL ,
    destacado            INTEGER NOT NULL 
);

ALTER TABLE L1_PROGRAMACION ADD CONSTRAINT XPKPROGRAMACION PRIMARY KEY (id_canal,fechahorainicio);

CREATE TABLE L1_RATING
(
    fechahorainicio      DATE NOT NULL ,
    fechahorafin         DATE NOT NULL ,
    rating               FLOAT NOT NULL ,
    id_canal             INTEGER NOT NULL 
);

ALTER TABLE L1_RATING ADD CONSTRAINT XPKRATING PRIMARY KEY (id_canal,fechahorainicio);

CREATE TABLE L1_TIPOCANAL
(
    id_tipocanal         INTEGER NOT NULL ,
    descripcion          VARCHAR(100) NOT NULL 
);

ALTER TABLE L1_TIPOCANAL ADD CONSTRAINT XPKTIPOCANAL PRIMARY KEY (id_tipocanal);

CREATE TABLE L1_TIPOPROGRAMA
(
    id_tipoprograma      INTEGER NOT NULL ,
    descripcion          VARCHAR(100) NOT NULL ,
    cantidadepisodios    INTEGER NULL ,
    frecuencia           INTEGER NULL 
);

ALTER TABLE L1_TIPOPROGRAMA ADD CONSTRAINT XPKTIPOPROGRAMA PRIMARY KEY (id_tipoprograma);

CREATE TABLE L1_TIPOPUBLICO
(
    id_tipopublico       INTEGER NOT NULL ,
    descripcion          VARCHAR(100) NOT NULL 
);

ALTER TABLE L1_TIPOPUBLICO ADD CONSTRAINT  XPKTIPOPUBLICO PRIMARY KEY (id_tipopublico);

ALTER TABLE L1_CANAL ADD CONSTRAINT CXP_1 FOREIGN KEY (id_categoria) REFERENCES L1_CATEGORIA (id_categoria);

ALTER TABLE L1_CANAL ADD CONSTRAINT CXP_2 FOREIGN KEY (id_tipocanal) REFERENCES L1_TIPOCANAL (id_tipocanal);

ALTER TABLE L1_CANAL ADD CONSTRAINT CXP_3 FOREIGN KEY (id_pais) REFERENCES L1_PAIS (id_pais);

ALTER TABLE L1_CANALXPAQUETE ADD CONSTRAINT CXP_12 FOREIGN KEY (id_canal) REFERENCES L1_CANAL (id_canal);

ALTER TABLE L1_CANALXPAQUETE ADD CONSTRAINT CXP_13 FOREIGN KEY (id_paquete) REFERENCES L1_PAQUETE (id_paquete);

ALTER TABLE L1_PROGRAMA ADD CONSTRAINT CXP_4 FOREIGN KEY (id_tipoprograma) REFERENCES L1_TIPOPROGRAMA (id_tipoprograma);

ALTER TABLE L1_PROGRAMA ADD CONSTRAINT CXP_5 FOREIGN KEY (id_tipopublico) REFERENCES L1_TIPOPUBLICO (id_tipopublico);

ALTER TABLE L1_PROGRAMA ADD CONSTRAINT CXP_6 FOREIGN KEY (id_categoria) REFERENCES L1_CATEGORIA (id_categoria);

ALTER TABLE L1_PROGRAMACION ADD CONSTRAINT CXP_8 FOREIGN KEY (id_programa) REFERENCES L1_PROGRAMA (id_programa);

ALTER TABLE L1_PROGRAMACION ADD CONSTRAINT CXP_9 FOREIGN KEY (id_canal) REFERENCES L1_CANAL (id_canal);

ALTER TABLE L1_RATING ADD CONSTRAINT CXP_10 FOREIGN KEY (id_canal) REFERENCES L1_CANAL (id_canal);
