-- Tabla: PACIENTES
CREATE TABLE PACIENTES (
  PACIENTE_ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  APELLIDOS VARCHAR2(100) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(20) NOT NULL,
  NRO_DOCUMENTO VARCHAR2(20) UNIQUE NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  SEXO CHAR(1) NOT NULL
);

-- Tabla: ESPECIALIDADES_MEDICAS
CREATE TABLE ESPECIALIDADES (
  ESPECIALIDAD_ID NUMBER PRIMARY KEY,
  DENOMINACION VARCHAR2(100) NOT NULL
);

-- Tabla: PERSONALES_MEDICOS
CREATE TABLE PERSONALES_MEDICOS (
  PERSONAL_ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  APELLIDOS VARCHAR2(100) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(20) NOT NULL,
  NRO_DOCUMENTO VARCHAR2(20) UNIQUE NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  SEXO CHAR(1) NOT NULL,
  TIPO_PERSONAL VARCHAR2(50) NOT NULL,
  ROL VARCHAR2(50) NOT NULL,
  ESPECIALIDAD_ID NUMBER NOT NULL,
  CONSTRAINT FK_PERSONAL_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_ID)
    REFERENCES ESPECIALIDADES(ESPECIALIDAD_ID)
);

-- Tabla: HORARIOS
CREATE TABLE HORARIOS (
  HORARIO_ID NUMBER PRIMARY KEY,
  PERSONAL_ID NUMBER NOT NULL,
  HORA_INICIO DATE NOT NULL,
  HORA_FIN DATE NOT NULL,
  CONSTRAINT FK_HORARIO_PERSONAL FOREIGN KEY (PERSONAL_ID)
    REFERENCES PERSONALES_MEDICOS(PERSONAL_ID)
);

-- Tabla: SERVICIOS_MEDICOS
CREATE TABLE SERVICIOS_MEDICOS (
  SERVICIO_ID NUMBER PRIMARY KEY,
  DENOMINACION VARCHAR2(100) NOT NULL,
  PRECIO NUMBER(10, 2) NOT NULL,
  ESPECIALIDAD_ID NUMBER NOT NULL,
  CONSTRAINT FK_SERVICIO_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_ID)
    REFERENCES ESPECIALIDADES(ESPECIALIDAD_ID)
);

-- Tabla: ATENCIONES_MEDICAS
CREATE TABLE ATENCIONES_MEDICAS (
  ATENCION_ID NUMBER PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  PERSONAL_ID NUMBER NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  HORA_INICIO DATE,
  HORA_FIN DATE,
  DIAGNOSTICO CLOB,
  CONSTRAINT FK_ATENCION_PACIENTE FOREIGN KEY (PACIENTE_ID)
    REFERENCES PACIENTES(PACIENTE_ID),
  CONSTRAINT FK_ATENCION_PERSONAL FOREIGN KEY (PERSONAL_ID)
    REFERENCES PERSONALES_MEDICOS(PERSONAL_ID)
);

-- Tabla: RECETAS_MEDICAS
CREATE TABLE RECETAS_MEDICAS (
  RECETA_ID NUMBER PRIMARY KEY,
  ATENCION_ID NUMBER NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  CONSTRAINT FK_RECETA_ATENCION FOREIGN KEY (ATENCION_ID)
    REFERENCES ATENCIONES_MEDICAS(ATENCION_ID)
);

-- Tabla: MEDICAMENTOS
CREATE TABLE MEDICAMENTOS (
  MEDICAMENTO_ID NUMBER PRIMARY KEY,
  DENOMINACION VARCHAR2(100) NOT NULL,
  UNIDAD_DOSIS VARCHAR2(50) NOT NULL,
  DISPONIBLE_EN VARCHAR2(100)
);

-- Tabla: RECETAS_MEDICAMENTOS
CREATE TABLE RECETAS_MEDICAMENTOS (
  RECETA_ID NUMBER NOT NULL,
  MEDICAMENTO_ID NUMBER NOT NULL,
  CANTIDAD_DOSIS NUMBER NOT NULL,
  FRECUENCIA VARCHAR2(50) NOT NULL,
  DURACION VARCHAR2(50),
  VIA_ADMINISTRACION VARCHAR2(50),
  CONSTRAINT PK_RECETA_MEDICAMENTO PRIMARY KEY (RECETA_ID, MEDICAMENTO_ID),
  CONSTRAINT FK_RM_RECETA FOREIGN KEY (RECETA_ID)
    REFERENCES RECETAS_MEDICAS(RECETA_ID),
  CONSTRAINT FK_RM_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_ID)
    REFERENCES MEDICAMENTOS(MEDICAMENTO_ID)
);

-- Tabla: BOLETAS
CREATE TABLE BOLETAS (
  BOLETA_ID NUMBER PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  MONTO_TOTAL NUMBER(10, 2),
  METODO_PAGO VARCHAR2(50) NOT NULL,
  NRO_SERIE VARCHAR2(20) UNIQUE NOT NULL,
  CONSTRAINT FK_BOLETA_PACIENTE FOREIGN KEY (PACIENTE_ID)
    REFERENCES PACIENTES(PACIENTE_ID)
);

-- Tabla: BOLETAS_SERVICIOS
CREATE TABLE BOLETAS_SERVICIOS (
  BOLETA_ID NUMBER NOT NULL,
  SERVICIO_ID NUMBER NOT NULL,
  PRECIO_UNITARIO NUMBER(10, 2) NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  SUBTOTAL NUMBER(10, 2) GENERATED ALWAYS AS (PRECIO_UNITARIO * CANTIDAD) VIRTUAL,
  CONSTRAINT PK_BOLETA_SERVICIO PRIMARY KEY (BOLETA_ID, SERVICIO_ID),
  CONSTRAINT FK_BS_BOLETA FOREIGN KEY (BOLETA_ID)
    REFERENCES BOLETAS(BOLETA_ID),
  CONSTRAINT FK_BS_SERVICIO FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIOS_MEDICOS(SERVICIO_ID)
);

-- Tabla: BOLETAS_MEDICAMENTOS
CREATE TABLE BOLETAS_MEDICAMENTOS (
  BOLETA_ID NUMBER NOT NULL,
  MEDICAMENTO_ID NUMBER NOT NULL,
  PRECIO_UNITARIO NUMBER(10, 2) NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  SUBTOTAL NUMBER(10, 2) GENERATED ALWAYS AS (PRECIO_UNITARIO * CANTIDAD) VIRTUAL,
  CONSTRAINT PK_BOLETA_MEDICAMENTO PRIMARY KEY (BOLETA_ID, MEDICAMENTO_ID),
  CONSTRAINT FK_BM_BOLETA FOREIGN KEY (BOLETA_ID)
    REFERENCES BOLETAS(BOLETA_ID),
  CONSTRAINT FK_BM_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_ID)
    REFERENCES MEDICAMENTOS(MEDICAMENTO_ID)
);